import Foundation

// MARK: - CorpusAttestation
//
// How many DISTINCT research channels (of 23) teach each exercise, mined
// from the YouTube corpus title index (tools/youtube-research/mentions.py,
// export 2026-08-20: 326 slugs attested by 2+ channels, 95 by one, 884
// silent). Keyed by lowercased catalog display name.
//
// The generator uses this as a SOFT PRIOR, not a filter: an exercise
// nobody in the field teaches never outranks one everybody teaches
// (owner ruling), but silent rows still fill a slot when nothing attested
// fits — same never-leave-a-hole law as the complexity gate. As corpus
// coverage grows this table retires selection heuristics; regenerate it
// from mentions.json rather than editing by hand.
//
// Known bias: title mining under-counts lifts that videos discuss without
// naming in the title, so the 2-channel trust bar (the corpus-consensus
// standard) only splits the tiebreak, never the ranking.
enum CorpusAttestation {
    /// Distinct teaching channels per lowercased exercise name.
    /// Absent = silent (0). 387 attested entries.
    static let channelCounts: [String: Int] = [
        "ab roller": 1,
        "adductor": 13,
        "archer push-up": 4,
        "arm circles": 3,
        "assisted dip machine": 1,
        "assisted pull-up machine": 11,
        "atlas stones": 2,
        "back extension": 7,
        "back squat": 13,
        "ball leg curl": 11,
        "band assisted pull-up": 10,
        "band good morning": 8,
        "band good morning (pull through)": 8,
        "band hip adductions": 1,
        "band pull apart": 2,
        "band skull crusher": 10,
        "barbell bulgarian split squat": 9,
        "barbell curl": 6,
        "barbell deadlift": 2,
        "barbell floor press": 6,
        "barbell front raise": 8,
        "barbell full squat": 5,
        "barbell glute bridge": 3,
        "barbell hack squat": 10,
        "barbell hip thrust": 12,
        "barbell incline shoulder raise": 3,
        "barbell rear delt row": 1,
        "barbell row": 8,
        "barbell seated calf raise": 11,
        "barbell shoulder press": 9,
        "barbell shrug": 2,
        "barbell side bend": 1,
        "barbell squat": 13,
        "barbell squat to a bench": 1,
        "barbell step ups": 5,
        "barbell walking lunge": 5,
        "bear crawl": 2,
        "belt squat": 7,
        "belt squat machine": 2,
        "bench dips": 2,
        "bench press": 14,
        "bent over barbell row": 1,
        "bent-over dumbbell rear delt fly": 1,
        "bicep curl": 12,
        "bicycling": 1,
        "bird dog": 2,
        "board press": 6,
        "bodyweight mid row": 1,
        "bodyweight squat": 2,
        "bodyweight walking lunge": 5,
        "box jump": 1,
        "box squat": 7,
        "broad jump": 3,
        "bulgarian split squat": 9,
        "burpee": 2,
        "butterfly": 3,
        "cable bayesian curl": 1,
        "cable chest press": 11,
        "cable crossover": 5,
        "cable crunch": 2,
        "cable fly": 5,
        "cable hip abduction": 6,
        "cable hip adduction": 3,
        "cable incline triceps extension": 8,
        "cable internal rotation": 6,
        "cable lying triceps extension": 8,
        "cable preacher curl": 9,
        "cable rear delt fly": 1,
        "cable reverse crunch": 2,
        "cable russian twists": 2,
        "cable seated lateral raise": 10,
        "cable shoulder press": 9,
        "cable shrug": 2,
        "cable shrugs": 1,
        "cable standing leg curl": 11,
        "cable triceps kickback": 3,
        "cable upright row": 6,
        "cable wrist curl": 3,
        "calf press": 1,
        "calf raise": 11,
        "child's pose": 1,
        "chin-up": 11,
        "clean and jerk": 6,
        "clean and press": 3,
        "clean deadlift": 2,
        "clean pull": 3,
        "clock push-up": 4,
        "close-grip front lat pulldown": 11,
        "close-grip push-up off of a dumbbell": 4,
        "concentration curls": 4,
        "conventional deadlift": 7,
        "crunches": 7,
        "curtsy lunge": 1,
        "dead bug": 1,
        "dead hang": 3,
        "deadlift with chains": 1,
        "decline barbell bench press": 14,
        "decline chest press machine": 6,
        "decline close-grip bench to skull crusher": 1,
        "decline crunch": 1,
        "decline dumbbell bench press": 14,
        "decline dumbbell triceps extension": 8,
        "decline ez bar triceps extension": 8,
        "decline push-up": 5,
        "decline reverse crunch": 2,
        "decline smith press": 2,
        "deficit deadlift": 6,
        "deficit push-up": 6,
        "diamond push-up": 5,
        "dip machine": 1,
        "donkey calf raise": 1,
        "drag curl": 1,
        "dumbbell bench press": 14,
        "dumbbell bicep curl": 12,
        "dumbbell floor press": 6,
        "dumbbell flyes": 1,
        "dumbbell incline shoulder raise": 3,
        "dumbbell lunges": 3,
        "dumbbell lying one-arm rear lateral raise": 10,
        "dumbbell lying rear lateral raise": 10,
        "dumbbell pullover": 5,
        "dumbbell raise": 2,
        "dumbbell row": 10,
        "dumbbell seated box jump": 1,
        "dumbbell shoulder press": 9,
        "dumbbell shrug": 2,
        "dumbbell side bend": 1,
        "dumbbell squat": 2,
        "dumbbell squat to a bench": 1,
        "dumbbell step ups": 5,
        "dumbbell upright row": 6,
        "elbows back": 2,
        "external rotation": 8,
        "ez-bar preacher curl": 9,
        "face pull": 7,
        "farmer's carry": 2,
        "floor press": 6,
        "flutter kicks": 1,
        "frog pump": 1,
        "front squat": 13,
        "full range-of-motion lat pulldown": 11,
        "glute bridge": 3,
        "glute ham raise": 3,
        "glute kickback": 1,
        "goblet squat": 7,
        "good morning": 8,
        "good morning off pins": 8,
        "ground base lat pulldown": 11,
        "hack squat": 10,
        "hack squat (machine)": 5,
        "hammer curl": 6,
        "hammer curls": 2,
        "hamstring stretch": 6,
        "handstand push-ups": 4,
        "hang clean": 1,
        "hanging bar good morning": 8,
        "hanging knee raise": 3,
        "hanging leg raise": 2,
        "hex press": 1,
        "high cable crossover": 1,
        "hip abduction machine": 2,
        "hip thrust machine": 12,
        "horizontal leg press": 2,
        "incline barbell triceps extension": 8,
        "incline bench press": 14,
        "incline bench pull": 3,
        "incline cable chest press": 11,
        "incline chest press machine": 6,
        "incline dumbbell curl": 8,
        "incline dumbbell fly": 1,
        "incline dumbbell press": 6,
        "incline hammer curls": 2,
        "incline push-up": 6,
        "incline push-up close-grip": 4,
        "incline push-up depth jump": 4,
        "incline push-up medium": 4,
        "incline push-up reverse grip": 4,
        "incline push-up wide": 4,
        "inverted row": 4,
        "iso-lateral lateral raise": 10,
        "iso-lateral leg curl": 11,
        "iso-lateral leg extension": 12,
        "iso-lateral rear delt fly": 1,
        "jm press": 3,
        "kettlebell arnold press": 1,
        "kettlebell hang clean": 1,
        "kettlebell pistol squat": 4,
        "kettlebell shoulder press": 9,
        "kettlebell swing": 1,
        "kettlebell windmill": 1,
        "kneeling lat pulldown": 11,
        "kneeling leg curl": 11,
        "landmine press": 3,
        "lat pulldown": 11,
        "lateral raise": 10,
        "lateral raise - with bands": 10,
        "lateral raise machine": 10,
        "lateral raise machine (plate-loaded, iso-lateral)": 10,
        "leg curl": 11,
        "leg extension": 12,
        "leg extension machine": 12,
        "leg extensions": 12,
        "leg lift": 1,
        "leg press": 13,
        "leg press calf raise": 2,
        "log lift": 1,
        "lying cable curl": 1,
        "lying dumbbell tricep extension": 7,
        "lying hamstring": 6,
        "lying leg curl": 11,
        "lying leg curl machine": 11,
        "lying leg curls": 11,
        "lying one-arm lateral raise": 10,
        "lying rear delt raise": 2,
        "lying t-bar row": 2,
        "lying triceps press": 3,
        "machine bench press": 14,
        "machine bicep curl": 12,
        "machine fly": 2,
        "machine hip thrust": 12,
        "machine lateral raise": 10,
        "machine preacher curls": 8,
        "machine pullover": 2,
        "machine triceps extension": 8,
        "meadows row": 1,
        "muscle snatch": 2,
        "narrow stance squats": 1,
        "neck press": 2,
        "nordic hamstring curl": 4,
        "one arm chin-up": 10,
        "one arm lat pulldown": 11,
        "one-arm dumbbell row": 1,
        "one-arm incline lateral raise": 10,
        "overhead press": 12,
        "overhead squat": 4,
        "overhead tricep extension": 6,
        "overhead triceps": 7,
        "pallof press": 1,
        "parallel bar dip": 1,
        "pec deck": 7,
        "pendlay row": 1,
        "pendulum squat": 7,
        "pike push-up": 4,
        "pin presses": 1,
        "pistol squat": 4,
        "plate front raise": 1,
        "plate-loaded chest press machine": 6,
        "plate-loaded lat pulldown machine": 11,
        "plate-loaded shoulder press machine": 2,
        "plyo push-up": 4,
        "power clean": 5,
        "power snatch": 2,
        "preacher curl": 9,
        "preacher curl machine": 2,
        "prone leg curl": 11,
        "pull through": 1,
        "pull-up": 14,
        "push press": 1,
        "push-up": 12,
        "push-up wide": 4,
        "push-ups - close triceps position": 4,
        "push-ups with feet elevated": 4,
        "push-ups with feet on an exercise ball": 4,
        "pyramid": 14,
        "quad stretch": 5,
        "rack pull": 6,
        "rack pulls": 4,
        "recumbent bike": 2,
        "renegade row": 1,
        "reverse band deadlift": 1,
        "reverse crunch": 2,
        "reverse curl": 2,
        "reverse hyperextension": 1,
        "reverse lunge": 4,
        "reverse pec deck": 2,
        "ring dip": 1,
        "ring dips": 1,
        "rocky pull-ups/pulldowns": 10,
        "romanian deadlift": 9,
        "rope crunch": 1,
        "russian twist": 3,
        "scapular pull-up": 10,
        "seal row": 2,
        "seated band hamstring curl": 11,
        "seated barbell military press": 3,
        "seated barbell shoulder press": 9,
        "seated cable row": 3,
        "seated cable rows": 1,
        "seated cable shoulder press": 9,
        "seated calf raise": 11,
        "seated calf raise (machine)": 3,
        "seated calf stretch": 5,
        "seated chest press machine": 6,
        "seated dip machine": 1,
        "seated dumbbell calf raise": 11,
        "seated dumbbell curl": 1,
        "seated front deltoid": 3,
        "seated good mornings": 8,
        "seated hamstring": 6,
        "seated hip thrust machine": 12,
        "seated lateral raise machine (plate-loaded)": 10,
        "seated leg curl": 11,
        "seated leg curl machine": 11,
        "seated row machine": 3,
        "seated side lateral raise": 10,
        "seated triceps press": 3,
        "shoulder raise": 3,
        "side lateral raise": 10,
        "side plank": 2,
        "single-arm push-up": 4,
        "single-leg calf raise": 1,
        "single-leg leg extension": 12,
        "sissy squat": 1,
        "sit-up": 5,
        "sled overhead triceps extension": 6,
        "sled push": 1,
        "smith machine": 10,
        "smith machine bench press": 14,
        "smith machine bent over row": 9,
        "smith machine calf raise": 11,
        "smith machine front squat": 13,
        "smith machine hack squat": 10,
        "smith machine incline bench press": 14,
        "smith machine leg press": 13,
        "smith machine lunge": 2,
        "smith machine overhead shoulder press": 1,
        "smith machine pistol squat": 4,
        "smith machine squat": 10,
        "smith machine stiff-legged deadlift": 4,
        "smith machine upright row": 6,
        "snatch": 10,
        "spanish squat": 1,
        "spider curl": 1,
        "split jerk": 1,
        "split jump": 1,
        "split squat with dumbbells": 1,
        "split squats": 12,
        "stairmaster": 3,
        "standing barbell calf raise": 11,
        "standing cable chest press": 11,
        "standing calf raise": 11,
        "standing calf raise (machine)": 3,
        "standing calf raises": 11,
        "standing concentration curl": 6,
        "standing dumbbell calf raise": 11,
        "standing dumbbell press": 1,
        "standing dumbbell reverse curl": 2,
        "standing dumbbell triceps extension": 8,
        "standing dumbbell upright row": 6,
        "standing hip circles": 1,
        "standing hip extension machine": 1,
        "standing hip flexors": 8,
        "standing lateral stretch": 1,
        "standing leg curl": 11,
        "standing leg curl machine": 11,
        "standing military press": 3,
        "standing pelvic tilt": 5,
        "standing rope crunch": 1,
        "standing row machine": 3,
        "step mill": 2,
        "stiff leg barbell good morning": 8,
        "suitcase carry": 2,
        "sumo deadlift": 9,
        "superman": 6,
        "suspended push-up": 4,
        "torso rotation": 2,
        "torso rotation machine": 1,
        "trap bar deadlift": 8,
        "tricep pushdown": 5,
        "triceps pushdown": 1,
        "triceps stretch": 1,
        "walking, treadmill": 1,
        "wall sit": 1,
        "weighted bench dip": 3,
        "weighted crunches": 1,
        "weighted dip": 4,
        "weighted jump squat": 4,
        "weighted plank": 1,
        "weighted pull ups": 3,
        "weighted pull-up": 11,
        "weighted push-up": 4,
        "weighted sissy squat": 1,
        "wide-grip lat pulldown": 11,
        "wide-grip rear pull-up": 10,
        "world's greatest stretch": 1,
        "wrist curl": 3,
        "wrist roller": 1
    ]

    /// 0 when the corpus is silent on this exercise.
    static func channels(name: String) -> Int {
        channelCounts[name.trimmingCharacters(in: .whitespaces).lowercased()] ?? 0
    }
}
