-- Disordered-eating and low-energy-availability screening (2026-08-25).
-- The last of the swarm's four document collectors: SCOFF, the IOC
-- consensus on Relative Energy Deficiency in Sport, and related
-- scope-of-practice guidance. 11 documents, 1 paywalled.
--
-- This is the evidence behind a product boundary already agreed: the app
-- lets users choose a fat-loss goal, and a disordered-eating signal must
-- put Coach into refer-out rather than into programming a deficit.

INSERT INTO public.corpus_findings (area, topic, claim, basis, confidence, sport, quantities) VALUES
  ('guideline', 'screening', 'SCOFF questionnaire (Morgan, Reid & Lacey, BMJ 1999) uses 5 yes/no items: self-induced vomiting, loss of control over eating, >1 stone lost in 3 months, self-perceived fatness, food dominating life.', 'guideline', 'strong', NULL, '{"num_questions":5,"weight_loss_stone":1,"weight_loss_period_months":3}'::jsonb),
  ('guideline', 'screening', 'SCOFF: a score of >=2 ''yes'' answers (of 5) is a positive screen; Children''s Mercy clinical guideline states a positive score should prompt referral to an eating-disorder specialist to confirm diagnosis.', 'guideline', 'strong', NULL, '{"threshold_yes_answers":2,"max_score":5}'::jsonb),
  ('guideline', 'screening', 'Morgan et al.''s original SCOFF validation (116 eating-disorder-clinic patients vs 96 controls) reported 100% sensitivity and 87.5% specificity at the >=2 threshold.', 'guideline', 'strong', NULL, '{"sensitivity_pct":100,"specificity_pct":87.5,"n_cases":116,"n_controls":96}'::jsonb),
  ('guideline', 'screening', 'A general-population SCOFF validation (Solmi et al. 2014, cited by Children''s Mercy guideline) found lower performance than the clinic-based original: sensitivity 77.8%, specificity 87.6%, PPV 9.7%, NPV 99.6%.', 'guideline', 'moderate', NULL, '{"sensitivity_pct":77.8,"specificity_pct":87.6,"ppv_pct":9.7,"npv_pct":99.6}'::jsonb),
  ('guideline', 'scope', 'SCOFF is explicitly a screening tool only, not diagnostic; a positive score requires further evaluation by an eating-disorder specialist to confirm diagnosis, per clinical guideline use of the instrument.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'energy_availability', 'IOC RED-S 2018 update (Mountjoy et al.) defines RED-S as impaired physiological functioning from relative energy deficiency, affecting metabolic rate, menstrual function, bone health, immunity, protein synthesis, and cardiovascular health.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'energy_availability', 'IOC RED-S 2018: optimal energy availability for healthy female physiological function is approximately 45 kcal/kg fat-free mass/day, per controlled laboratory studies cited in the consensus.', 'guideline', 'strong', NULL, '{"optimal_EA_kcal_per_kg_FFM_day":45}'::jsonb),
  ('guideline', 'energy_availability', 'IOC RED-S 2018: EA below 30 kcal/kg FFM/day was the historically targeted low-energy-availability threshold, but the consensus itself flags that recent evidence shows this cutoff doesn''t reliably predict amenorrhea.', 'guideline', 'hedged', NULL, '{"historical_LEA_threshold_kcal_per_kg_FFM_day":30}'::jsonb),
  ('guideline', 'red_flags', 'IOC RED-S 2018: for athletes meeting diagnostic criteria for severe eating disorders (anorexia or bulimia nervosa), participation in competition is not recommended.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'scope', 'IOC RED-S 2018: apparent disordered eating/eating disorders should be treated by a multidisciplinary team (medical, dietary, mental health); ideally a mental-health professional experienced with athletes leads treatment.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'red_flags', 'IOC RED-S 2018: non-compliance with treatment may require removing the athlete from training/competition; return-to-play uses clearance categories and treatment contracts detailed in companion Female Athlete Triad publications.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'scope', 'IOC RED-S 2018 notes coaches, despite being well-positioned to notice disordered eating, often struggle to distinguish sport-appropriate leanness from an eating disorder and to get athletes into treatment -- cited as rationale for referral.', 'guideline', 'moderate', NULL, NULL),
  ('guideline', 'red_flags', '2023 IOC REDs consensus: the CAT2 tool stratifies athletes on a 4-colour traffic light: green (full participation), yellow (continued monitoring), orange (intensive medical intervention/monitoring), red (full medical support, consider removal from sport).', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'scope', '2023 IOC REDs CAT2 explicitly states its guidelines ''are not a substitute for professional clinical diagnosis, advice and/or treatment from a team of REDs health and performance experts led by a physician.''', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'screening', '2023 IOC REDs CAT2 is a 3-step process: Step 1 screening questionnaire/clinical interview (less sensitive, easy first pass); Step 2 severity/risk assessment; Step 3 diagnosis and treatment plan by an expert physician.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'energy_availability', '2023 IOC REDs consensus proposes EA zones (debated, mainly from short-term lab studies): high EA >=45 kcal/kg FFM/day, adequate ~45, reduced EA for mass/fat loss 30-45, health-impairing LEA <=30 kcal/kg FFM/day.', 'guideline', 'moderate', NULL, '{"high_EA_min":45,"reduced_EA_low":30,"reduced_EA_high":45,"LEA_health_threshold_max":30}'::jsonb),
  ('guideline', 'red_flags', '2023 IOC REDs consensus lists ''serious medical indicators'' (e.g., <=75% median BMI for age/sex, severe bradycardia, severe hypotension <=90/45mmHg) requiring immediate medical attention and removal from training/competition -- physician-assessed, not self-screenable.', 'guideline', 'strong', NULL, '{"BMI_pct_of_median_max":75,"severe_hypotension_systolic_max":90,"severe_hypotension_diastolic_max":45}'::jsonb),
  ('guideline', 'red_flags', 'Female Athlete Triad Coalition 2025 update: athletes with anorexia nervosa and BMI <16 kg/m^2, or moderate-to-severe bulimia nervosa (purging >4x/week), should be categorically restricted from training and competition.', 'guideline', 'strong', NULL, '{"AN_BMI_max":16,"BN_purge_freq_min_per_week":4}'::jsonb),
  ('guideline', 'scope', 'Female Athlete Triad Coalition 2025 consensus panel: clearance/return-to-play decisions from the Cumulative Risk Assessment tool should only be made by physicians, not coaches, trainers, or other support staff.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'red_flags', 'Female Athlete Triad Coalition 2025: risk is stratified low/moderate/high via a Cumulative Risk Assessment tool; clearance outcomes include full, provisional, limited (physician-specified modifications), provisionally restricted, and disqualified.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'energy_availability', 'Female Athlete Triad Coalition 2025 warning signs: body weight <85% expected; BMI <17.5 (adults) or <5th percentile (adolescents); serial weight/BMI decline; low fasting T3/IGF-1/leptin with elevated ghrelin; elevated drive for thinness.', 'guideline', 'strong', NULL, '{"expected_weight_pct_max":85,"adult_BMI_max":17.5,"adolescent_BMI_percentile_max":5}'::jsonb),
  ('guideline', 'red_flags', 'Female Athlete Triad Coalition 2025 lists compulsive exercise, inadvertent undereating, time-restricted eating, and intermittent fasting among behaviors screened as possible eating-pathology indicators -- context-dependent, not automatically diagnostic of a disorder.', 'guideline', 'hedged', NULL, NULL),
  ('guideline', 'weight_loss', 'Female Athlete Triad Coalition 2025: a modest increase in daily energy intake (330+/-65 kcal/day) was sufficient to improve menstrual regularity in at-risk athletes -- treatment is energy repletion, not further restriction.', 'guideline', 'strong', NULL, '{"energy_increase_kcal_per_day":330,"energy_increase_sd_kcal":65}'::jsonb),
  ('guideline', 'scope', 'Female Athlete Triad Coalition 2025: multidisciplinary care (physician, registered dietitian, mental-health professional) is the gold standard; non-physician providers (PAs/NPs) may screen via pre-participation exams but do not make clearance decisions.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'scope', 'NSCA''s Personal Training Quarterly ''Scope of Practice for Personal Trainer'' explicitly lists ''eating disorder'' under ''When a Referral is Necessary,'' alongside metabolic disease and positive OSA screens.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'scope', 'NSCA PTQ scope-of-practice article: ''a personal trainer is not qualified like a Registered Dietitian, who can write meal plans for clients'' -- trainers should disseminate general nutrition info without prescribing meal/calorie plans.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'scope', 'NSCA PTQ scope-of-practice article: ''practicing medicine is not within the scope of practice for the personal trainer''; trainers may use validated screening questionnaires only to identify when to refer to a physician.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'weight_loss', 'The same NSCA PTQ article also lists ''client has been following healthy habit changes but is not losing weight'' as its own separate referral trigger, distinct from eating disorder.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'scope', 'ACE (American Council on Exercise): fitness professionals should not offer individualized meal planning, conduct nutrition assessments, make specific diet/intake recommendations, offer nutrition counseling, or present themselves as a dietitian unless licensed.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'weight_loss', 'IDEA Health & Fitness Association scope-of-practice guidance: trainers should not prescribe diets, recommend supplements, perform nutrition assessments, or advise precise caloric-restriction amounts; general non-medical nutrition education is within scope.', 'guideline', 'strong', NULL, NULL),
  ('guideline', 'scope', 'IDEA article quotes a registered dietitian stating he would not advise a client he suspected of having an eating disorder, framing recognizing one''s own limitations as professionally appropriate, not a knowledge gap.', 'guideline', 'moderate', NULL, NULL),
  ('guideline', 'scope', 'NSCA (per nsca.com certification-prep excerpt; the page itself was unreachable/403) states referral is necessary for suspected eating disorders and when a client follows healthy habits without losing weight, matching the PTQ article''s Figure 1.', 'guideline', 'hedged', NULL, NULL),
  ('guideline', 'weight_loss', 'NSCA CPT curriculum Ch.19 (per third-party certification-prep summary, not primary text): clients returning to exercise after eating-disorder treatment need physician clearance; programming should deemphasize weight loss for low-energy-demand exercise.', 'guideline', 'hedged', NULL, NULL);
