-- 20260822000008_progression_findings.sql
--
-- Programming fundamentals join the research library (owner
-- 2026-08-22: "wire some programming fundamentals into this query
-- batch"): 37 findings from the four-batch deep-read over the
-- progression pass - double progression triggers, overshoot handling
-- (the screenshot's exact case), reps-vs-load, autoregulation, stalls,
-- increments. The proposeRoutineEdit loop's knowledge base.
INSERT INTO public.corpus_findings (area, topic, claim, basis, confidence, sport, quantities) VALUES
  ('progression', 'double_progression', 'Flow High Performance advises increasing reps within a target rep range each session while keeping technique tight; once the rep ceiling is exceeded, add load rather than more reps.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'overshoot', 'House of Hypertrophy cites literature that reps of 6-35 taken near failure grow muscle similarly; beyond ~35 reps, fatigue blunts fiber recruitment, so switching to heavier load is recommended.', 'mechanistic', 'moderate', NULL, '{"rep_range_effective": "6-35", "ceiling_reps": 35}'::jsonb),
  ('progression', 'reps_vs_load', 'Two controlled trials (untrained, then trained lifters) found progressing by adding load versus adding reps at fixed load produced similar strength and hypertrophy gains in both groups.', 'cited_study', 'strong', NULL, '{"study1_n": 39, "study1_weeks": 10, "study1_rep_progression": "9 to 15 reps/set", "study2_n": 38}'::jsonb),
  ('progression', 'reps_vs_load', 'For strength specifically, trained lifters gained more squat/bench 1RM training in a 2-4 rep range than in 8-12 reps, suggesting load progression matters more when strength is the goal.', 'cited_study', 'moderate', NULL, '{"low_rep_range": "2-4", "comparison_range": "8-12"}'::jsonb),
  ('progression', 'autoregulation', 'Menno Henselmans'' AVT method uses only the first set of an exercise, taken to a progressively heavier target, as the progress benchmark; later sets are done with open reps, autoregulated by fatigue and readiness.', 'experience', 'strong', NULL, NULL),
  ('progression', 'autoregulation', 'Menno cites a 2019 review finding programs prescribing %1RM (vs. fixed rep-max targets) yield slightly better average strength gains, but flags it didn''t control for proximity to failure or volume.', 'cited_study', 'hedged', NULL, '{"year": 2019}'::jsonb),
  ('progression', 'stalls', 'Menno''s progress rule: hitting the benchmark set''s rep target with progressively more load means the program works and shouldn''t change; missing it repeatedly signals the program needs updating.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'increments', 'Exercises using small muscle mass are harder to add load to each session (no fine micro-plates), so lifters more often add a rep instead; this becomes more common as training experience grows.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'stalls', 'For a single stalled exercise, adjust only that exercise''s progression model (lower rep targets with intensification, daily undulating periodization, reactive deloads) rather than overhauling the whole program.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'stalls', 'When several exercises for one body part all stall together, treat it as a volume problem: raise weekly volume for that muscle group long-term, or cut it back if overtrained.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'stalls', 'Diagnose a systemic (all-exercise) stall by adding one extra rest day: resumed progress implies volume was too high; faster progress after adding sets instead implies volume was too low.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'autoregulation', 'Fatigue index (reps lost across sets at one load) signals volume fit: flat rep counts suggest volume too low or effort not near failure; large rep loss suggests volume too high.', 'mechanistic', 'moderate', NULL, NULL),
  ('progression', 'reps_vs_load', 'Compound benchmark lifts are kept long-term for continuous load progression, while isolation/accessory exercises like lateral raises get swapped for variety since they offer little realistic long-term load headroom.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'double_progression', 'Cited study: one leg trained a fixed 9-12 rep range to failure, adding load once reps exceeded 12, while a varied-workout leg gained no more muscle despite doing more volume.', 'cited_study', 'strong', NULL, '{"rep_range_low": 9, "rep_range_high": 12}'::jsonb),
  ('progression', 'reps_vs_load', 'Progressive overload can be driven by adding reps or adding load; either constitutes a valid increase in training stress and both serve as evidence that progress occurred.', 'mechanistic', 'moderate', NULL, NULL),
  ('progression', 'double_progression', 'Concrete rep or load targets each session are what drive genuine effort; without a specific number to beat, most lifters unconsciously stop short and leave reps in reserve.', 'mechanistic', 'moderate', NULL, NULL),
  ('progression', 'double_progression', 'Core weekly progression loop is adding reps and/or load each session then deloading periodically, but only reps performed with full technique count toward that progress.', 'experience', 'strong', NULL, NULL),
  ('progression', 'overshoot', 'If reps exceed a rep target only via breakdown in technique (e.g. 12 vs a 10-rep goal), count only the last technically-clean rep as the real result, not the raw number.', 'experience', 'strong', NULL, NULL),
  ('progression', 'stalls', 'Failing to repeat two technically clean reps for two straight sessions on an exercise signals excess fatigue, not a program flaw; deload at that point instead of pushing further.', 'experience', 'strong', NULL, '{"consecutive_failed_sessions_before_deload": 2}'::jsonb),
  ('progression', 'autoregulation', 'Judge progress by averaging performance across all working sets of an exercise, not any single set; one underperforming set alone doesn''t indicate a failure to progress.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'stalls', 'Trigger deloads or training breaks by subjective fatigue and readiness rather than a fixed calendar, since neither a scheduled mid-block break nor continuous training clearly won on muscle growth.', 'cited_study', 'hedged', NULL, NULL),
  ('progression', 'double_progression', 'Within a target rep range (about 5-10), progress by adding reps if last session landed inside the range with clean technique; only add load once reps reach the range''s top with form intact.', 'experience', 'strong', NULL, '{"rep_range": "5-10"}'::jsonb),
  ('progression', 'increments', 'Default load jump when progressing is about 2.5-5% of last session''s weight; if the top-of-range reps looked easy, take a noticeably bigger jump instead of the standard increment.', 'experience', 'strong', NULL, '{"load_increase_pct": "2.5-5"}'::jsonb),
  ('progression', 'overshoot', 'When capable of far more reps than the target ceiling, add only one or two reps and let extra load cover the rest of the surplus capability rather than jumping several reps at once.', 'experience', 'moderate', NULL, '{"reps_added": "1-2"}'::jsonb),
  ('progression', 'stalls', 'If technique breaks down anywhere in the target rep range, progression halts: repeat the same load and rep count next session, resuming only once that effort is done with clean form.', 'experience', 'strong', NULL, NULL),
  ('progression', 'reps_vs_load', 'For isolation exercises, favor progressing reps to the top of the range before adding load, since small plate jumps are large relative increases and an extra rep is gentler on joints.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'double_progression', 'When a rep or load change pushes performance outside the intended range, widen the range itself (raise the ceiling or lower the floor) rather than treat it as a problem to fix.', 'experience', 'hedged', NULL, NULL),
  ('progression', 'stalls', 'For lifts that can''t be trained heavy multiple times weekly, insert an extra low-intensity technique session (about 70-80% of 1RM, RPE 3-6, a few sets of 2-4 reps) on off days instead of skipping practice.', 'experience', 'strong', NULL, '{"intensity_pct_1rm": "70-80", "rpe": "3-6", "reps_per_set": "2-4"}'::jsonb),
  ('progression', 'stalls', 'Before concluding a true plateau and overhauling a program, confirm zero PRs across a full mesocycle (through its deload) in the same rep range and style, with external stressors like illness or travel ruled out.', 'experience', 'strong', NULL, NULL),
  ('progression', 'increments', 'Barbell bench press allows very fine load jumps (roughly 5 lb or less via small plates), which the speaker treats as a key edge for consistent, controllable progressive overload versus bulkier equipment increments.', 'experience', 'moderate', NULL, '{"load_increment_lbs": 5}'::jsonb),
  ('progression', 'reps_vs_load', 'On machine or isolation exercises, once the next available plate-stack jump feels too large to control cleanly, the speaker switches from adding load to adding reps at the same weight instead.', 'experience', 'moderate', NULL, NULL),
  ('progression', 'stalls', 'A genuine strength plateau means zero measurable gain across one full mesocycle when retested in the same rep range; merely slower week-to-week gains than another lift is not a plateau.', 'experience', 'strong', NULL, '{"duration": "1 mesocycle (about 4-8 weeks)"}'::jsonb),
  ('progression', 'stalls', 'The default fix for an unexplained strength stall is cutting weekly training volume in half for one full mesocycle before retesting, since unrecognized accumulated fatigue is the most common hidden cause.', 'experience', 'strong', NULL, '{"volume_cut_pct": 50}'::jsonb),
  ('progression', 'reps_vs_load', 'When a lift stalls because the athlete lacks muscle mass rather than technique or neural capacity, prescribe 2-4 mesocycles of 5-10 rep hypertrophy training in a caloric surplus before resuming 3-6 rep strength work.', 'experience', 'moderate', NULL, '{"hypertrophy_phase_mesocycles": "2-4", "rep_range": "5-10", "return_rep_range": "3-6"}'::jsonb),
  ('progression', 'increments', 'To keep a mesocycle productive, add roughly at least one rep or about 2.5 lb to a lift most sessions; progressing slower than that pace amounts to junk volume with no real overload.', 'experience', 'strong', NULL, '{"min_rep_increment": 1, "min_load_increment_lbs": 2.5}'::jsonb),
  ('progression', 'stalls', 'Swap an exercise only after it shows a genuine slow-progress plateau, not for novelty; keep compound lifts for at least 3-4 mesocycles and isolation lifts for only 1-2 before substituting a variant.', 'experience', 'moderate', NULL, '{"compound_min_mesocycles": "3-4", "isolation_max_mesocycles": "1-2"}'::jsonb),
  ('progression', 'autoregulation', 'Experienced lifters self-manage fatigue mid-week by swapping a demanding compound lift for an easier variant, such as a leg extension instead of hack squats, functioning as an unscheduled micro-deload.', 'experience', 'hedged', NULL, NULL);
