INSERT INTO public.exercises (name, slug, category, primary_muscle, secondary_muscles, equipment) VALUES
  ('Bench Press', 'bench-press', 'compound', 'chest', ARRAY['triceps','front_delts'], 'barbell'),
  ('Incline Bench Press', 'incline-bench-press', 'compound', 'chest', ARRAY['triceps','front_delts'], 'barbell'),
  ('Dumbbell Bench Press', 'db-bench-press', 'compound', 'chest', ARRAY['triceps','front_delts'], 'dumbbell'),
  ('Overhead Press', 'ohp', 'compound', 'shoulders', ARRAY['triceps','upper_chest'], 'barbell'),
  ('Dumbbell Shoulder Press', 'db-shoulder-press', 'compound', 'shoulders', ARRAY['triceps'], 'dumbbell'),
  ('Back Squat', 'back-squat', 'compound', 'quads', ARRAY['glutes','hamstrings','core'], 'barbell'),
  ('Front Squat', 'front-squat', 'compound', 'quads', ARRAY['glutes','core'], 'barbell'),
  ('Goblet Squat', 'goblet-squat', 'compound', 'quads', ARRAY['glutes','core'], 'dumbbell'),
  ('Conventional Deadlift', 'deadlift', 'compound', 'hamstrings', ARRAY['glutes','back','traps'], 'barbell'),
  ('Romanian Deadlift', 'rdl', 'compound', 'hamstrings', ARRAY['glutes','lower_back'], 'barbell'),
  ('Sumo Deadlift', 'sumo-deadlift', 'compound', 'glutes', ARRAY['hamstrings','back'], 'barbell'),
  ('Pull-Up', 'pull-up', 'compound', 'lats', ARRAY['biceps','rear_delts'], 'bodyweight'),
  ('Chin-Up', 'chin-up', 'compound', 'lats', ARRAY['biceps'], 'bodyweight'),
  ('Barbell Row', 'barbell-row', 'compound', 'back', ARRAY['biceps','rear_delts'], 'barbell'),
  ('Dumbbell Row', 'db-row', 'compound', 'back', ARRAY['biceps','rear_delts'], 'dumbbell'),
  ('Lat Pulldown', 'lat-pulldown', 'compound', 'lats', ARRAY['biceps'], 'cable'),
  ('Seated Cable Row', 'cable-row', 'compound', 'back', ARRAY['biceps','rear_delts'], 'cable'),
  ('Bicep Curl', 'bicep-curl', 'isolation', 'biceps', ARRAY['forearms'], 'dumbbell'),
  ('Hammer Curl', 'hammer-curl', 'isolation', 'biceps', ARRAY['forearms'], 'dumbbell'),
  ('Tricep Pushdown', 'tricep-pushdown', 'isolation', 'triceps', ARRAY[]::text[], 'cable'),
  ('Overhead Tricep Extension', 'oh-tricep-ext', 'isolation', 'triceps', ARRAY[]::text[], 'dumbbell'),
  ('Lateral Raise', 'lat-raise', 'isolation', 'shoulders', ARRAY[]::text[], 'dumbbell'),
  ('Face Pull', 'face-pull', 'isolation', 'rear_delts', ARRAY['traps'], 'cable'),
  ('Leg Press', 'leg-press', 'compound', 'quads', ARRAY['glutes'], 'machine'),
  ('Leg Curl', 'leg-curl', 'isolation', 'hamstrings', ARRAY[]::text[], 'machine'),
  ('Leg Extension', 'leg-extension', 'isolation', 'quads', ARRAY[]::text[], 'machine'),
  ('Calf Raise', 'calf-raise', 'isolation', 'calves', ARRAY[]::text[], 'machine'),
  ('Plank', 'plank', 'isolation', 'core', ARRAY[]::text[], 'bodyweight'),
  ('Hanging Leg Raise', 'hanging-leg-raise', 'isolation', 'core', ARRAY['hip_flexors'], 'bodyweight'),
  ('Push-Up', 'push-up', 'compound', 'chest', ARRAY['triceps','front_delts','core'], 'bodyweight');
