-- Volume landmarks pass (2026-08-25). Owner pushed back on the claim that
-- the corpus had nothing on general volume landmarks: it was the FINDINGS
-- TABLE that lacked them, never the transcript corpus. A title-routed
-- sweep over 28 videos from the evidence-focused channels (Renaissance
-- Periodization, Stronger By Science, Data Driven Strength, House of
-- Hypertrophy, Jeff Nippard, Menno Henselmans, 3DMJ, Flow High
-- Performance) produced 170 raw findings; four topic distillers merged
-- them and four adversarial verifiers rejected 23 for invented or
-- inferred quantities, overstated confidence, or duplication. These are
-- the 69 survivors.
--
-- Confidence skews conservative on purpose: the verifiers downgraded any
-- claim a single hedged source carried. Genuine disagreements are NOT
-- flattened here -- they are recorded in docs/science/volume-landmarks.md
-- so Coach can say the field is split instead of picking a side.

INSERT INTO public.corpus_findings (area, topic, claim, basis, confidence, sport, quantities) VALUES
  ('volume', 'weekly_volume', 'A defensible low-volume floor is 6-8 direct hard sets per muscle per week, with about 10 sets described as low-but-solid and roughly the minimum-effective point for beginners.', 'experience', 'moderate', NULL, '{"safe_floor_sets_per_week":"6-8","low_but_solid_sets_per_week":10,"beginner_mev_sets_per_week":10}'::jsonb),
  ('volume', 'weekly_volume', 'A systematic review binned volume as low (<12), moderate (12-20), high (>20) weekly sets: moderate clearly beat low, but high was only marginally superior and statistically significant only for triceps.', 'cited_study', 'strong', NULL, '{"low_sets_per_week":"<12","moderate_sets_per_week":"12-20","high_sets_per_week":">20"}'::jsonb),
  ('volume', 'weekly_volume', 'Scale weekly volume by training age: start beginners near the low end (about 9-12 sets) and let advanced lifters work the high end, since their response to a given stimulus is blunted.', 'experience', 'moderate', NULL, '{"beginner_sets_per_week":"9-12"}'::jsonb),
  ('volume', 'weekly_volume', 'The apparent weekly ceiling depends on rest and frequency: long-rest twice-weekly protocols showed no benefit above 12-18 sets, while short-rest (~1 min) thrice-weekly protocols still gained at 30-45 sets.', 'cited_study', 'moderate', NULL, '{"long_rest_ceiling_sets_per_week":"12-18","long_rest_sessions_per_week":2,"short_rest_sets_per_week":"30-45","short_rest_sessions_per_week":3}'::jsonb),
  ('volume', 'weekly_volume', 'Prescribing habitual volume plus 20% (averaging 24 weekly sets) beat a standardized 22 sets per week for quad growth, 9.9% vs 6.2% CSA; 10 of 16 subjects favored the individualized leg.', 'cited_study', 'moderate', NULL, '{"individualized_sets_per_week":24,"standardized_sets_per_week":22,"csa_gain_individualized_pct":9.9,"csa_gain_standardized_pct":6.2,"favored_individualized":"10 of 16","favored_standardized":2,"no_difference":4}'::jsonb),
  ('volume', 'weekly_volume', 'For near-maximal loading (90%+ 1RM) in trained weightlifters, a moderate weekly dose of about 8-9 reps beat both roughly 4 and roughly 18-20 reps per week for strength over 10 weeks.', 'cited_study', 'moderate', NULL, '{"low_reps_per_week":"~4","moderate_reps_per_week":"~8-9","high_reps_per_week":"~18-20","duration_weeks":10,"intensity":"90%+ 1RM"}'::jsonb),
  ('volume', 'weekly_volume', 'Roughly 1-2 heavy sets per week per quality retains maximal strength but does not build it, giving a usable in-season, deload, or maintenance-phase floor.', 'cited_study', 'moderate', NULL, '{"maintenance_sets_per_week":"1-2"}'::jsonb),
  ('volume', 'weekly_volume', 'Count only hard sets toward weekly volume, and treat volume and per-set effort as partly substitutable: low weekly volume demands sets very close to failure, high volume tolerates more reps in reserve.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'weekly_volume', 'The real weekly ceiling is the individual''s recoverable capacity, which has no universal number; population-average recommendations should serve as a troubleshooting starting point, not a fixed prescription.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'weekly_volume', 'Training every muscle at about 25 weekly sets would require roughly 10-14 gym hours per week, making blanket high volume impractical and arguing for rotating specialization instead.', 'experience', 'moderate', NULL, '{"sets_per_week":25,"gym_hours_per_week":"10-14"}'::jsonb),
  ('volume', 'weekly_volume', 'Enhanced (PED-using) lifters tolerate and often require higher weekly volumes than natural lifters because they recover faster; drug status is named as a driver of the wide published range.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'weekly_volume', 'For hard gainers who stall, older research favored raising weekly volume (for example from 10 to 20 sets) over adding more recovery, contradicting the once-common recovery-first hypothesis.', 'cited_study', 'moderate', NULL, '{"baseline_sets_per_week":10,"increased_sets_per_week":20}'::jsonb),
  ('volume', 'volume_progression', 'When progress stalls, add weekly volume only if recovery is adequate; if under-recovered, cut volume first, and if stalling recurs quickly, the fix is less volume rather than more.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'session_dose', 'One coach places the productive per-muscle session band far wider, at 3-12 hard sets: below 3 leaves growth unclaimed, well above 12 drifts into junk volume.', 'experience', 'hedged', NULL, '{"sets_per_session":"3-12"}'::jsonb),
  ('volume', 'session_dose', 'Session floor is about 3-4 working sets per muscle for a reliable hypertrophy benefit; single-set sessions still grow muscle but less than multi-set work of roughly 2-6 sets.', 'cited_study', 'moderate', NULL, '{"minimum_safe_sets_per_session":"3-4","multi_set_range":"2-6"}'::jsonb),
  ('volume', 'session_dose', 'Per-session caps should be muscle-specific: back, glutes and quads reportedly tolerate about 10-12 sets in a session while other muscles plateau nearer 6-8.', 'experience', 'hedged', NULL, '{"high_tolerance_sets_per_session":"10-12","typical_sets_per_session":"6-8","muscles_high_tolerance":"back, glutes, quads"}'::jsonb),
  ('volume', 'session_dose', 'Past roughly 10 sets for one muscle in a single session, the lifter must train further from failure or cut that muscle''s frequency; excess may hasten overtraining onset.', 'mechanistic', 'moderate', NULL, '{"sets_per_session_threshold":"10"}'::jsonb),
  ('volume', 'session_dose', 'An absolute single-session ceiling near 20 sets per muscle is proposed for advanced lifters, lower for beginners, beyond which added sets in that workout contribute nothing.', 'experience', 'hedged', NULL, '{"advanced_ceiling_sets_per_session":"20"}'::jsonb),
  ('volume', 'session_dose', 'Splitting a muscle''s weekly sets across two sessions beats stacking them: 20 chest sets in one session wastes roughly half as junk volume, while 10 plus 10 progresses better.', 'experience', 'moderate', NULL, '{"single_session_sets":"20","split_sets_each":"10"}'::jsonb),
  ('volume', 'session_dose', 'Session set count and per-set effort trade off: the 6-8 set cap assumes sets to failure, carrying more sets requires backing off failure, and low-set sessions demand each set be near failure.', 'mechanistic', 'moderate', NULL, '{"failure_based_cap":"6-8"}'::jsonb),
  ('volume', 'session_dose', 'Adding non-failure sets can underperform fewer hard ones: one study found 3 sets to failure beat both 3 and 4 non-failure sets at matched load and intensity.', 'cited_study', 'moderate', NULL, '{"failure_sets":"3","non_failure_sets":"3 and 4"}'::jsonb),
  ('volume', 'session_dose', 'Rep-count framings of session dose disagree: one puts productive volume near 30 reps per body part (up to about 90 in special cases), another at 40-70 reps with plateau past 40.', 'synthesis', 'hedged', NULL, '{"source_a_reps_per_bodypart":"30","source_a_special_case_reps":"90","source_b_reps_per_session":"40-70","source_b_plateau_reps":"40"}'::jsonb),
  ('volume', 'session_dose', 'Junk volume also occurs inside the set from too-light loads: 47% of lifters on self-selected 10RM hit 16-20+ reps; sets past 40-50 reps under 20% 1RM add recovery cost without growth.', 'cited_study', 'moderate', NULL, '{"pct_10_12_reps":"22","pct_13_15_reps":"31","pct_16_20plus_reps":"47","junk_rep_threshold":"40-50","pct_1rm_cutoff":"20","recommended_max_reps_per_set":"30"}'::jsonb),
  ('volume', 'exercises_per_session', 'Default to one or two quality exercises per muscle per session at 2-6 working sets each; complex regions like back take two to three, quads and hamstrings one to two.', 'experience', 'moderate', NULL, '{"exercises_per_muscle":"1-2","sets_per_exercise":"2-6","back_exercises":"2-3","quad_or_hamstring_exercises":"1-2"}'::jsonb),
  ('volume', 'exercises_per_session', 'Scale exercise count to that muscle''s set total for the session: roughly 1-2 exercises at 6 sets and 3-4 at 12 sets, keeping sets per exercise inside the quality window.', 'mechanistic', 'moderate', NULL, '{"low_volume_sets":"6","low_volume_exercises":"1-2","high_volume_sets":"12","high_volume_exercises":"3-4"}'::jsonb),
  ('volume', 'exercises_per_session', 'Cap exercises per muscle near its count of functional sub-regions — most muscles have only one to three — so fan-shaped multi-joint muscles like pecs and back justify more movements than biceps or calves.', 'mechanistic', 'moderate', NULL, '{"functional_subregions":"1-3"}'::jsonb),
  ('volume', 'exercises_per_session', 'Regional bias is measured, not theoretical: flat versus 30-degree incline press, horizontal row versus vertical pull, and Smith squat versus leg extension each favour different regions of the same muscle.', 'cited_study', 'moderate', NULL, '{"incline_angle_deg":"30"}'::jsonb),
  ('volume', 'exercises_per_session', 'Adjust direct exercise count for indirect work: muscles hammered by compounds such as delts may need only one or two direct movements, while poorly covered ones like hamstrings need more direct variety.', 'mechanistic', 'moderate', NULL, '{"well_covered_direct_exercises":"1-2"}'::jsonb),
  ('volume', 'exercises_per_session', 'Exercise count is a distribution lever, not an independent growth driver: at fixed weekly volume more exercises simply means fewer sets each, and no volume-equated trial has compared exercise counts.', 'mechanistic', 'moderate', NULL, NULL),
  ('volume', 'exercises_per_session', 'Full-body sessions produced roughly 30% lower per-muscle protein-synthesis response than sessions focused on fewer muscle groups at matched volume, arguing against spreading many muscles across one session.', 'cited_study', 'moderate', NULL, '{"mps_reduction_pct":"30","studies":"3"}'::jsonb),
  ('volume', 'session_dose', 'In a 65-minute general-population session only 25-30 minutes remain for strength work, about 2-3 superset pairs; agonist-antagonist supersets matched traditional growth over 8 weeks while cutting time about 56%.', 'cited_study', 'moderate', NULL, '{"session_minutes":"65","strength_minutes":"25-30","superset_pairs":"2-3","time_saved_pct":"56","study_weeks":"8"}'::jsonb),
  ('volume', 'session_dose', 'Per-session dose scales with training age: beginners take one back-off or drop set per isolation exercise where advanced lifters take all three, and the beginner session ceiling sits below the advanced one.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'exercises_per_session', 'A worked push-day template runs 5-7 movements total: one heavy primary compound, two secondary compounds near failure, isolation drop-set work, then a conditioning finisher.', 'experience', 'moderate', NULL, '{"movements_total":"5-7"}'::jsonb),
  ('volume', 'exercises_per_session', 'Light-load single-joint isolation exercises need more sets than heavy compounds to reach a growth stimulus, so a slot budget should not treat compound and isolation sets as interchangeable units.', 'experience', 'hedged', NULL, NULL),
  ('volume', 'frequency', 'Frequency is not an independent growth driver: at 12 or fewer weekly sets per muscle, meta-analyses found once versus multiple weekly sessions produced similar hypertrophy and strength.', 'cited_study', 'moderate', NULL, '{"sets_per_week_threshold":12,"sessions_compared":"3 vs 4 sessions/week, same weekly volume, similar growth"}'::jsonb),
  ('volume', 'frequency', 'Assign different sub-regions or angles to different sessions rather than covering every angle inside one session; splitting a muscle''s weekly sets this way beats cramming.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'frequency', 'Smaller muscles (abs, biceps, delts) tolerate higher weekly frequency because they sustain less damage, while large muscle groups may be capped near twice weekly.', 'experience', 'hedged', NULL, '{"large_muscle_freq_per_week":2}'::jsonb),
  ('volume', 'frequency', 'Set frequency per trained quality: CNS-intensive strength and power 1-3 hard sessions weekly, hypertrophy 2-4 (24-72h recovery), technique and skill work 3-10+ including multiple daily sessions.', 'experience', 'moderate', NULL, '{"strength_power_freq_per_week":"1-3","hypertrophy_freq_per_week":"2-4","hypertrophy_recovery_hours":"24-72","technique_freq_per_week":"3-10+","strength_lift_floor":"sometimes 1x/week"}'::jsonb),
  ('volume', 'frequency', 'Nothing in the corpus supports pushing per-muscle frequency past about four weekly sessions; whether 5-6x weekly or intra-day micro-dosing adds quality volume is explicitly unresolved.', 'synthesis', 'hedged', NULL, '{"uncertain_comparison":"5-6x/week vs 3-4x/week","microdose_example":"10 sets of 10 curls spread across a day","studied_frequency_ceiling":"3x/day"}'::jsonb),
  ('volume', 'frequency', 'Volume added by raising frequency shows diminishing returns: a 50% weekly volume increase via added sessions is estimated to yield roughly 20% more hypertrophy or strength.', 'mechanistic', 'hedged', NULL, '{"volume_increase_pct":50,"estimated_gain_increase_pct":20}'::jsonb),
  ('volume', 'frequency', 'Full-body sessions blunt the per-muscle response: three studies found roughly 30% lower quad protein-synthetic response than sessions focused on fewer muscle groups at matched volume.', 'cited_study', 'moderate', NULL, '{"mps_reduction_pct":30,"studies":3}'::jsonb),
  ('volume', 'frequency', 'Volume, proximity-to-failure and frequency are interdependent; maximizing all three at once is overtraining, so a program generator must trade one against the others.', 'mechanistic', 'strong', NULL, NULL),
  ('volume', 'frequency', 'Within a training week, place hypertrophy sessions before power and strength sessions; a dissertation found that order improved powerlifters'' strength outcomes and total volume completed.', 'cited_study', 'moderate', NULL, NULL),
  ('volume', 'variation', 'Rotation cadence should scale with an exercise''s technique and neural maturation time: free-weight compounds hold 3-8 mesocycles, machine or stable compounds 2-7, isolation 1-6.', 'experience', 'moderate', NULL, '{"free_weight_compound_mesocycles":"3-8","machine_or_stable_compound_mesocycles":"2-7","isolation_mesocycles":"1-6"}'::jsonb),
  ('volume', 'variation', 'Skill and neural adaptation are movement-specific and slow, so rotate the heavy primary free-weight lift last; variations bias range-of-motion and tension for hypertrophy, not main-lift skill.', 'mechanistic', 'moderate', NULL, NULL),
  ('volume', 'variation', 'Do not rotate an exercise after one bad session; only a multi-month plateau in that movement''s performance justifies swapping it out.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'variation', 'Rotating squat, leg press and lunge every two weeks produced greater growth in specific quad muscles than performing squats alone over the same period.', 'cited_study', 'moderate', NULL, '{"rotation_weeks":2,"exercises":"squat, leg press, lunge"}'::jsonb),
  ('volume', 'variation', 'Keep 2-3 active exercises per muscle drawn from a pool of 6-7, refreshing the pool every 6-8 months to keep stimulus novel and limit joint wear.', 'experience', 'moderate', NULL, '{"active_exercises":"2-3","pool_size":"6-7","pool_refresh_interval_months":"6-8"}'::jsonb),
  ('volume', 'variation', 'Switch to the next exercise within a session once technique and mind-muscle control degrade, which typically occurs by the fifth or sixth set on one movement.', 'experience', 'moderate', NULL, '{"switch_after_sets":"5-6","sets_per_exercise":"2-6","exercises_per_muscle_per_session":"1-2"}'::jsonb),
  ('volume', 'variation', 'A newly introduced exercise may give a small, temporary growth bump resembling diminished newbie gains, but this novelty effect is explicitly not established.', 'mechanistic', 'hedged', NULL, NULL),
  ('volume', 'volume_progression', 'Progress weekly sets off each lifter''s habitual baseline, not a fixed prescription: habitual+20% (avg 24 sets) beat a standardized 22 sets/week for quad growth, 9.9% vs 6.2% CSA.', 'cited_study', 'moderate', NULL, '{"increase_over_habitual_pct":20,"individualized_sets_per_week":24,"standardized_sets_per_week":22,"csa_gain_individualized_pct":9.9,"csa_gain_standardized_pct":6.2,"p":"<0.05"}'::jsonb),
  ('volume', 'volume_progression', 'Response to that same +20% progression is not universal: 10 of 16 subjects grew more on individualized volume, 2 more on the standardized dose, 4 showed no between-leg difference.', 'cited_study', 'moderate', NULL, '{"n_total":16,"favor_individualized":10,"favor_standardized":2,"no_difference":4}'::jsonb),
  ('volume', 'volume_progression', 'How many sets to add per step is unsettled: post-hoc of a 12/18/24 sets/week trial found top responders had added about 6.6 sets over baseline, mid 4.3, low 1.8.', 'cited_study', 'hedged', NULL, '{"trial_arms_sets_per_week":"12/18/24","high_responder_added_sets":6.6,"mid_responder_added_sets":4.3,"low_responder_added_sets":1.8}'::jsonb),
  ('volume', 'volume_progression', 'End-of-block overreach did not backfire: raising weekly volume about 20% over the final four weeks, to roughly 5-9 sets per muscle, left hypertrophy holding rather than receding.', 'cited_study', 'moderate', NULL, '{"volume_increase_pct":20,"final_weeks":4,"final_sets_per_muscle_per_week":"5-9"}'::jsonb),
  ('volume', 'volume_progression', 'Specialization block spec: pick 1-4 muscles for a 4-12 week cycle, raise their volume 20-40% above habitual, and drop the other muscles to 50-60% of normal or hold them steady.', 'experience', 'moderate', NULL, '{"muscles_per_cycle":"1-4","cycle_weeks":"4-12","specialized_increase_pct":"20-40","deprioritized_volume_pct":"50-60"}'::jsonb),
  ('volume', 'volume_progression', 'Specialization volume must be temporary: pushing a lagging muscle toward about 20 sets per week should run roughly four weeks and then be cut back, not sustained indefinitely.', 'experience', 'moderate', NULL, '{"specialization_weeks":4,"specialization_sets_per_week":20}'::jsonb),
  ('volume', 'volume_progression', 'A baseline of roughly 10-20 hard sets per muscle per week should be undulated cyclically, pushed toward the top of the band only during planned overreaching phases rather than held there.', 'experience', 'moderate', NULL, '{"sets_per_week_range":"10-20"}'::jsonb),
  ('volume', 'volume_progression', 'Ramp new or deconditioned trainees in over the first weeks with an ascending set-rep scheme (2x8, 2x10, 3x8, 3x10) to build volume tolerance without crushing soreness.', 'experience', 'moderate', NULL, '{"scheme":"2x8,2x10,3x8,3x10"}'::jsonb),
  ('volume', 'volume_progression', 'Whether to jump straight into a block''s higher volume in week one or ramp into it has no clear theoretical winner; tolerance for the jump may depend on the muscle.', 'experience', 'hedged', NULL, NULL),
  ('volume', 'volume_progression', 'Stall rule: add volume only if recovery is adequate; if under-recovered, cut volume first, and if the stall recurs quickly after adding sets, the correct fix is less volume, not more.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'volume_progression', 'Volume accumulation raises fitness and fatigue together; once fatigue outpaces fitness, performance drops until volume is cut and fatigue dissipates — the mechanistic case for scheduled volume cuts.', 'mechanistic', 'moderate', NULL, NULL),
  ('volume', 'volume_progression', 'Counter-model: rather than tapering volume toward a strength test, hold relative volume (%1RM x reps x sets) constant across the cycle and shift only rep range and proximity to failure.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'volume_progression', 'Trade sets for load across phases instead of adding volume: one set of 8 at RPE 8 in a hypertrophy phase becomes two sets of 4 at heavier load in a strength phase, relative volume constant.', 'mechanistic', 'moderate', NULL, '{"hypertrophy_reps_per_set":8,"hypertrophy_rpe":8,"strength_sets":2,"strength_reps_per_set":4}'::jsonb),
  ('volume', 'volume_progression', 'Hold total volume constant when a cycle is meant to test something: changing volume alongside other variables destroys any ability to attribute the training response to one change.', 'experience', 'moderate', NULL, NULL),
  ('volume', 'volume_progression', 'Autoregulate volume within a session with back-off sets: cut load 3-7% each set until you return to the opening RPE; smaller cuts favor intensity, larger cuts accumulate more volume.', 'experience', 'moderate', NULL, '{"load_cut_pct_min":3,"load_cut_pct_max":7}'::jsonb),
  ('volume', 'volume_progression', 'Prefer smaller between-block volume cuts: large drops, such as after a competition, risk a lag period where training feels unproductive while volume is rebuilt toward prior levels.', 'experience', 'hedged', NULL, NULL),
  ('volume', 'volume_progression', 'Long planned breaks may cost nothing: alternating roughly six weeks of training with four weeks off over six months produced no significant strength or hypertrophy difference versus continuous training.', 'cited_study', 'moderate', NULL, '{"train_weeks":6,"off_weeks":4,"study_months":6}'::jsonb),
  ('volume', 'volume_progression', 'Keep training cycles moderate, about 10-16 weeks, so adaptations have time to show while still allowing repeated experimentation across a training career.', 'experience', 'moderate', NULL, '{"cycle_length_weeks":"10-16"}'::jsonb),
  ('volume', 'volume_progression', 'Blanket volume progression is time-infeasible: training every muscle at roughly 25 sets per week would demand about 10-14 hours weekly, which is the practical case for rotating specialization instead.', 'experience', 'moderate', NULL, '{"sets_per_week":25,"hours_per_week":"10-14"}'::jsonb);
