-- Exercise substitution graph (owner 2026-08-17).
--
-- Coach could previously only walk a ranked candidate list, which is not the
-- same as knowing a legitimate swap. These edges are mined from the
-- educational-fitness corpus (tools/youtube-research) and answer the question
-- a lifter actually asks mid-session: "the hack squat is taken / my gym has
-- no barbell / that hurts my shoulder — what do I do instead?"
--
-- Provenance is carried on every edge so the UI can be honest about WHY a
-- swap is offered, and so a weakly-sourced edge never outranks a well-sourced
-- one. `sources` counts independent videos asserting the same swap.

CREATE TABLE IF NOT EXISTS public.exercise_substitutions (
  from_slug   text NOT NULL REFERENCES public.exercises(slug) ON DELETE CASCADE,
  to_slug     text NOT NULL REFERENCES public.exercises(slug) ON DELETE CASCADE,
  -- full = genuinely interchangeable · partial = covers most of it with a
  -- stated tradeoff · inferior = works, but worse.
  equivalence text NOT NULL DEFAULT 'partial'
              CHECK (equivalence IN ('full', 'partial', 'inferior')),
  -- Why you'd reach for the swap. `equipment`/`injury_pain`/`crowding` are
  -- the situational ones the session UI surfaces; `preference` edges are
  -- programming choices and rank below them.
  trigger     text NOT NULL DEFAULT 'preference'
              CHECK (trigger IN ('equipment', 'injury_pain', 'skill',
                                 'time', 'preference', 'crowding')),
  reason      text NOT NULL DEFAULT '',
  basis       text NOT NULL DEFAULT 'experience'
              CHECK (basis IN ('cited_study', 'mechanistic', 'experience')),
  confidence  text NOT NULL DEFAULT 'moderate'
              CHECK (confidence IN ('strong', 'moderate', 'hedged')),
  sources     integer NOT NULL DEFAULT 1,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (from_slug, to_slug),
  CONSTRAINT no_self_substitution CHECK (from_slug <> to_slug)
);

CREATE INDEX IF NOT EXISTS exercise_substitutions_from_idx
  ON public.exercise_substitutions(from_slug);

ALTER TABLE public.exercise_substitutions ENABLE ROW LEVEL SECURITY;

-- Globally readable, exactly like the exercise catalog it extends. No
-- INSERT/UPDATE/DELETE policies: edges are mined offline and written by the
-- service role through migrations, never by clients.
CREATE POLICY "substitutions are globally readable"
  ON public.exercise_substitutions FOR SELECT TO authenticated
  USING (true);
-- Substitution graph, mined from the educational-fitness corpus.
-- Generated by tools/youtube-research/graph.py — do not hand-edit.
INSERT INTO public.exercise_substitutions
  (from_slug, to_slug, equivalence, trigger, reason, basis, confidence, sources)
VALUES
  ('back-squat', 'barbell-hack-squat', 'full', 'preference', 'Presented as a direct hypertrophy-focused stand-in for the back squat when someone can''t, won''t, or doesn''t need to test heavy squat strength.', 'experience', 'strong', 2),
  ('lying-t-bar-row', 'chest-supported-row-machine', 'full', 'equipment', 'Both brace the torso against a pad so the lower back can''t cheat the pull, delivering a comparable mid-back rowing stimulus.', 'mechanistic', 'strong', 2),
  ('seated-calf-raise', 'standing-calf-raise', 'partial', 'equipment', 'A cited study found the soleus, which seated raises target, responds poorly to training volume regardless of reps, so straight-knee standing work may cover it adequately.', 'cited_study', 'hedged', 2),
  ('seated-leg-curl', 'lying-leg-curl', 'inferior', 'equipment', 'Both flex the knee against resistance to load the hamstrings; lying leg curl is the standard fallback when no seated machine is available.', 'cited_study', 'strong', 2),
  ('assisted-pull-up-machine', 'lat-pulldown', 'full', 'skill', 'Both are vertical pulling movements that build the back comparably well, provided the load keeps progressively increasing over time.', 'experience', 'strong', 1),
  ('back-extension', 'floor-glute-ham-raise', 'inferior', 'preference', 'Back extensions mainly train the erector spinae or posterior chain, while glute-ham raises emphasize knee flexion and the short head of the biceps femoris.', 'mechanistic', 'strong', 1),
  ('back-squat', 'barbell-bulgarian-split-squat', 'full', 'preference', 'Offered as a second stand-in option in the same hypertrophy-only substitution list, alongside hack squats, for lifters skipping the heavy squat.', 'experience', 'strong', 1),
  ('back-squat', 'leg-press', 'partial', 'injury_pain', 'Leg press still drives the hip, knee, and ankle flexion of a squat under load, so it keeps training the pattern when squatting causes pain.', 'mechanistic', 'strong', 1),
  ('back-squat', 'leg-extension', 'partial', 'injury_pain', 'During a two-year injury layoff from squatting, isolation leg extensions kept building quad size without loading the spine axially.', 'experience', 'moderate', 1),
  ('back-squat', 'barbell-walking-lunge', 'partial', 'injury_pain', 'Lunges kept loading the quads through a similar knee-and-hip-extension pattern while squatting was off-limits during his injury recovery.', 'experience', 'moderate', 1),
  ('back-squat', 'heel-elevated-goblet-squat', 'partial', 'injury_pain', 'Elevating the heels changed the knee-and-hip angle to match his femur length, letting him squat pain-free where deep hip flexion previously hurt.', 'experience', 'moderate', 1),
  ('back-squat', 'front-squat', 'full', 'preference', 'Front squat and back squat are both squat-pattern lifts hitting largely the same muscles, unlike pairing overhead press with bench press.', 'mechanistic', 'moderate', 1),
  ('band-good-morning', 'rdl', 'full', 'skill', 'Both are barbell hip-hinge patterns for the posterior chain, but the RDL''s bar-against-the-legs path is simpler to learn and feels more stable.', 'experience', 'strong', 1),
  ('band-skull-crusher', 'incline-push-up-close-grip', 'partial', 'equipment', 'A close-grip push-up bends the elbows through a similar path to a skull crusher, so it can hammer the triceps without any weights.', 'mechanistic', 'moderate', 1),
  ('barbell-deadlift', 'trap-bar-deadlift', 'partial', 'preference', 'Both are heavy hip-hinge pulls from the floor, but the trap bar''s neutral grip keeps the torso more upright, shifting extra load onto the quads.', 'mechanistic', 'strong', 1),
  ('barbell-deadlift', 'barbell-hip-thrust', 'partial', 'preference', 'Both drive hip extension through the posterior chain, but the hip thrust isolates the glutes directly instead of pulling everything together off the floor.', 'mechanistic', 'strong', 1),
  ('barbell-deadlift', 'barbell-bulgarian-split-squat', 'partial', 'preference', 'Both can serve as the day''s heavy compound lift; leaning the torso forward on the split squat pulls extra glute and hamstring work into an otherwise quad-focused move.', 'mechanistic', 'strong', 1),
  ('barbell-deadlift', 'back-squat', 'partial', 'preference', 'Heavy squat volume builds much of the same posterior-chain and total-body strength that carries over to the deadlift, easing the need for direct deadlift work.', 'experience', 'hedged', 1),
  ('barbell-hack-squat', 'bodyweight-squat', 'partial', 'equipment', 'Since bodyweight alone is a lighter load, he says you need several near-failure sets of bodyweight squats to match one hard set of machine hack squats.', 'mechanistic', 'moderate', 1),
  ('barbell-side-split-squat', 'barbell-bulgarian-split-squat', 'partial', 'equipment', 'Elevating the rear foot shifts more bodyweight onto the front leg (about 85% vs 75%), giving a harder quad stimulus when only light dumbbells are available.', 'cited_study', 'strong', 1),
  ('barbell-walking-lunge', 'smith-machine-lunge', 'partial', 'crowding', 'The fixed bar path lets you reproduce the same leg-drive stimulus in place, which matters when walking lunges would otherwise eat up the whole gym floor.', 'mechanistic', 'moderate', 1),
  ('barbell-walking-lunge', 'barbell-side-split-squat', 'partial', 'skill', 'A study found lifters new to training used much greater range of motion on split squats than lunges, since the fixed stance is easier to balance.', 'cited_study', 'strong', 1),
  ('bodyweight-squat', 'single-leg-high-box-squat', 'partial', 'equipment', 'Once regular bodyweight squats stop being challenging and no weight can be added, dropping to one leg increases the per-leg demand and difficulty.', 'mechanistic', 'moderate', 1),
  ('cable-chest-press', 'decline-barbell-bench-press', 'partial', 'crowding', 'When his usual chest-press machine was occupied, he switched to bench press and still pushed his pecs hard with heavy sets and drop sets.', 'experience', 'moderate', 1),
  ('chest-supported-row-machine', 'db-row', 'full', 'equipment', 'Bracing your chest against an inclined bench gives the same stable, supported base as a chest-supported row machine, so the back gets loaded the same way.', 'experience', 'strong', 1),
  ('chin-up', 'lat-pulldown', 'partial', 'skill', 'Pulldowns let lifters too heavy to do enough bodyweight chin-ups still train the same vertical-pull pattern with a scalable load.', 'mechanistic', 'moderate', 1),
  ('deadlift', 'rdl', 'full', 'preference', 'Both hinge at the hip to load glutes, hamstrings, and spinal erectors; skipping the dead-stop floor reset each rep makes the RDL less taxing per set.', 'experience', 'strong', 1),
  ('dumbbell-lying-rear-lateral-raise', 'cable-lateral-raise', 'full', 'equipment', 'A single eight-week trial pitted the two moves against each other and found equivalent shoulder growth, despite each loading the muscle at a different length.', 'cited_study', 'strong', 1),
  ('front-squat', 'barbell-hack-squat', 'partial', 'skill', 'A hack squat machine loads the quads in a similar way without needing the upper-back and shoulder strength required to hold the front-rack position.', 'mechanistic', 'moderate', 1),
  ('glute-drive-machine', 'barbell-hip-thrust', 'full', 'equipment', 'Both load hip extension to build the glutes with minimal quad involvement; barbell hip thrust is the go-to when the specialty machine isn''t available.', 'mechanistic', 'strong', 1),
  ('incline-db-curl', 'cable-preacher-curl', 'partial', 'preference', 'Both flex the elbow to load the brachioradialis; an unpublished study found the preacher curl''s more lengthened position produced somewhat greater growth.', 'cited_study', 'hedged', 1),
  ('lat-pulldown', 'cross-pulldown-machine', 'full', 'equipment', 'As long as the joint moves through a similar range under similar loading, he sees no meaningful difference, so pick whichever pulldown angle you have access to.', 'mechanistic', 'moderate', 1),
  ('leg-press', 'back-squat', 'partial', 'equipment', 'A cited study found squat-only training raised leg-press 1RM just as much as leg-press training itself, while leg-press training didn''t transfer back to squat strength.', 'cited_study', 'strong', 1),
  ('nordic-hamstring-curl', 'leg-curl', 'inferior', 'injury_pain', 'Without a partner to control the eccentric or a padded setup, Nordic curls hurt the knees and become impractical, while a leg curl still trains hamstrings to failure safely.', 'mechanistic', 'moderate', 1),
  ('ohp', 'bench-press', 'inferior', 'preference', 'The program uses them as interchangeable weekly alternates, but overhead press stresses the side delts while bench stresses the pecs, different muscles.', 'mechanistic', 'strong', 1),
  ('reverse-grip-bent-over-row', 'chest-supported-row-machine', 'full', 'injury_pain', 'Chest support removes the lower-back loading of an unsupported bent-over row while still training the same pulling pattern, easing his back issues.', 'experience', 'strong', 1),
  ('reverse-grip-tricep-pushdown', 'oh-tricep-ext', 'full', 'preference', 'A cited study found the overhead position, which stretches the triceps'' long head further, drove substantially more growth over 12 weeks than pressdowns did.', 'cited_study', 'strong', 1),
  ('reverse-grip-tricep-pushdown', 'band-skull-crusher', 'full', 'preference', 'Both isolate the triceps directly, so either works equally well to pre-fatigue the muscle before moving to dips.', 'experience', 'hedged', 1),
  ('rdl', 'single-leg-romanian-deadlift', 'full', 'equipment', 'Single-leg RDLs need far less external weight to load the hamstrings and add extra medial-glute stabilizer activation from balancing on one leg.', 'experience', 'moderate', 1),
  ('rdl', 'barbell-hip-thrust', 'inferior', 'injury_pain', 'When pain blocks hinge patterns like the RDL, the hip thrust still loads the glutes through a supported range when nothing else is tolerable.', 'experience', 'moderate', 1),
  ('cable-row', 'inverted-row', 'partial', 'injury_pain', 'Inverted rows still pull the back through a similar rowing motion without the deep hip-hinge and lumbar loading that his cable row setup uses.', 'experience', 'hedged', 1),
  ('cable-row', 'barbell-row', 'partial', 'injury_pain', 'A machine row supports the torso and removes the hip-hinge position his cable row uses, taking strain off an irritated lower back.', 'experience', 'hedged', 1),
  ('smith-machine-bench-press', 'decline-barbell-bench-press', 'full', 'equipment', 'Both train the same high-incline chest press pattern; swap in a barbell and drop the load roughly 10-20 lb since the fixed Smith bar path needs less stabilization effort.', 'experience', 'strong', 1)
ON CONFLICT (from_slug, to_slug) DO UPDATE SET
  equivalence = EXCLUDED.equivalence, trigger = EXCLUDED.trigger,
  reason = EXCLUDED.reason, basis = EXCLUDED.basis,
  confidence = EXCLUDED.confidence, sources = EXCLUDED.sources;
