-- Corpus sweep 2026-08-26: equipment-constrained programming, tempo /
-- technique modifiers, and Olympic lifting. 155 findings from 17 deep-read
-- batches over transcripts already on disk.
--
-- Adds a PROVENANCE column, and the reason is itself one of the findings:
-- the olympic synthesis reports that ~90% of that area comes from a single
-- channel whose owner has a commercial stake in the answer, and that every
-- "study" in it is a secondhand relay by that coach. Agreement inside one
-- voice is not corroboration. Without a source column, that caveat lives
-- only in a summary nobody queries.
--
-- `quantities` is jsonb and existing rows hold structured objects. These
-- findings arrived as prose, so each goes under a `note` key rather than
-- being parsed into a structure that was never extracted.
ALTER TABLE public.corpus_findings
  ADD COLUMN IF NOT EXISTS source text;

INSERT INTO public.corpus_findings
  (area, topic, claim, basis, confidence, quantities, source)
VALUES
  ('equipment','modality_equivalence_hypertrophy','Across four hypertrophy studies comparing free weights, machines, and bodyweight training, muscle growth was statistically comparable when sets were taken to or near failure within a 6-35 rep range - no modality is inherently superior for hypertrophy. The equivalence is bounded by that rep range; it does not license the 50-rep bodyweight and 20-30-rep band sets other sources prescribe.','meta-analysis','strong','{"note": "6-35 rep range"}'::jsonb,'House of Hypertrophy - The BEST Training Mode for Muscle Growth'),
  ('equipment','rep_range_ceiling_conflict','CONTESTED: House of Hypertrophy bounds modality equivalence at 6-35 reps and treats exercises a novice can exceed 35 reps on as unable to maximize growth, while Renaissance Periodization prescribes up to 50 reps/set for no-equipment work and Garage Strength programs 20-30 rep band sets. The evidence base supports the 6-35 bound; the high-rep prescriptions are practitioner opinion, and one of them (band sets) is self-described as maintenance, not overload.','practice','moderate','{"note": "35 reps (evidence bound); 50 reps/set; 20-30 reps/set"}'::jsonb,'House of Hypertrophy vs Renaissance Periodization vs Garage Strength'),
  ('equipment','pattern_gaps_requiring_equipment','Three movement patterns cannot be covered by barbell/dumbbell alone and require a bar to hang from, a machine, or a band: vertical pull (pull-up/pulldown), isolated knee extension, and isolated knee flexion (Nordic curl covers the last with bodyweight only). This is the load-bearing constraint for an equipment-filter feature.','practice','moderate',NULL,'House of Hypertrophy - The BEST Training Mode for Muscle Growth'),
  ('equipment','hip_hinge_has_no_bodyweight_substitute','Bodyweight squat, lunge, and hip-thrust variants adequately train quads and glutes, and Nordic curls cover hamstring knee-flexion, but there is no effective bodyweight hip-extension exercise that recruits the hamstrings - hip-hinge hamstring work is the single hardest pattern to substitute with zero equipment.','practice','moderate',NULL,'House of Hypertrophy - Bodyweight Training is BAD for Muscle Growth'),
  ('equipment','bodyweight_upper_vs_lower_asymmetry','Two independent sources agree bodyweight training can be extremely effective long-term for upper body but caps lower-body hypertrophy: novices exceed 35 reps on several lower-body movements quickly, and single-leg progressions like the pistol squat hit a hard-to-overload ceiling. Trexler''s minimalist recommendation follows the same split - bodyweight upper body paired with an external-resistance device (flywheel) for lower body.','practice','moderate','{"note": "more than 35 reps"}'::jsonb,'House of Hypertrophy; Stronger By Science (Trexler, Ep. 48)'),
  ('equipment','band_bodyweight_maintains_size_not_strength','A Stronger By Science host reports that ~1 year training almost exclusively with bands, pull-ups, and push-ups maintained muscle mass and body composition well, but strength dropped somewhat - the practical outcome split an app should communicate for equipment-limited periods: size holds, strength regresses.','opinion','weak','{"note": "~1 year"}'::jsonb,'Stronger By Science - Fireside Chat #9'),
  ('equipment','weighted_calisthenics_matches_barbell_recruitment','A 2019 Norwegian study found that when load was equated, weighted push-ups and bench presses produced similar chest, triceps, and shoulder recruitment - adding external weight is a validated long-term progression path for bodyweight exercises rather than a compromise.','study','moderate','{"note": "2019 study, load-equated"}'::jsonb,'House of Hypertrophy - Bodyweight Training is BAD for Muscle Growth'),
  ('equipment','tempo_and_pauses_as_bodyweight_overload','A wide range of rep tempos, including deliberately slowed reps and added pauses, are reported as comparably effective for hypertrophy, making tempo manipulation a legitimate overload lever for bodyweight movements once rep progression is exhausted.','study','moderate',NULL,'House of Hypertrophy - Bodyweight Training is BAD for Muscle Growth'),
  ('equipment','bodyweight_overload_ladder','When load cannot increase, the reported progression ladder is: add reps ? slow tempo / add pauses ? shift to a mechanically harder position (hips forward in a squat to remove glute contribution; feet progressively elevated in a push-up toward an overhead-press angle) ? shift to unilateral (single-leg squat, pistol) ? add external weight. Israetel targets keeping push-ups near failure within 10-20 reps by elevating the feet rather than grinding high-rep sets.','practice','moderate','{"note": "10-20 reps target for push-ups; hips-forward shift suggested past sets of 50"}'::jsonb,'Renaissance Periodization (Israetel) - Get Huge Without The Gym; 6 WILDLY Effective Exercises'),
  ('equipment','limited_equipment_progression_tactics','Renaissance Periodization''s consistent prescription for dumbbell/band-only training is to progress via reps rather than load, train closer to failure than usual, cut inter-set rest, raise frequency (e.g. dumbbell squats 3-4x/week), add sets (4-6 vs the 2-4 that suffice with heavy load), and use rest-pause techniques. Israetel states explicitly that home training is NOT a like-for-like swap of a dumbbell version of your usual barbell exercise - selection, frequency, and volume all have to change.','practice','moderate','{"note": "3-4x/week; 4-6 sets vs 2-4; rest cut to 30s-1min"}'::jsonb,'Renaissance Periodization - Q&A 11.3.2021; RP Webinar 8-26-2020; Get Huge Without The Gym'),
  ('equipment','myo_rep_density_for_no_equipment_training','A myo-reps-style density protocol is offered for no-equipment sessions where individual reps are too light: ~20 reps close to failure, rest 5-10 seconds, then mini-sets of ~5-7 reps.','practice','weak','{"note": "20 reps; 5-10s rest; 5-7 rep mini-sets"}'::jsonb,'Renaissance Periodization (Israetel) - Get Huge Without The Gym'),
  ('equipment','unilateral_substitution_when_load_too_light','When available dumbbells are too light to stimulate a trainee, RP coaches recommend switching to unilateral movements - step-ups, single-leg squats, single-leg stiff-leg deadlifts - explicitly labelling this ''not totally optimal'' but ''a welcome compromise''. This is the standard fallback rule for a load-ceiling condition.','practice','moderate',NULL,'Renaissance Periodization - Q&A 11.3.2021'),
  ('equipment','movement_pattern_substitution_rule','The substitution heuristic stated by RP is to match the general movement pattern (a press, a curl, a squat/quad movement) rather than replicate the specific exercise - e.g. substitute knee extensions plus sissy squats for a leg press when only a knee-extension machine is available. An app''s substitution graph should key on pattern, not on exercise identity.','practice','moderate',NULL,'Renaissance Periodization - RP Webinar 8-26-2020'),
  ('equipment','dumbbell_load_ceiling','Dumbbells cannot replicate a heavy barbell squat program - Israetel''s illustration is that 3x10 dumbbell squats at equivalent load would need 180 lb dumbbells. A separate RP example calls 10 lb dumbbell deadlifts fine for a beginner but inadequate programming for an advanced trainee. Concrete evidence that a load-ceiling flag needs to be trainee-level-aware.','opinion','weak','{"note": "180 lb dumbbells for 3x10; 10 lb dumbbells inadequate for advanced"}'::jsonb,'Renaissance Periodization - RP Webinar 8-26-2020; Q&A 11.3.2021'),
  ('equipment','bands_not_superior_for_growth','No published study shows resistance-band training producing greater muscle growth than free-weight training - the viral ''bands build muscle 3x faster'' claim has no support. A 2020 Japanese study did show banded curls and tricep extensions produce measurable biceps/triceps hypertrophy, but no study has directly compared bands to free weights or machines. Bands work; they are not better, and the comparison is untested.','study','strong','{"note": "''3x faster'' claim unsupported; 2020 Japanese study shows measurable growth"}'::jsonb,'Biolayne (Norton); House of Hypertrophy'),
  ('equipment','band_resistance_curve_pattern_fit','A band''s ascending tension profile fits a squat (loosest at the hard bottom position, tightest at the easy top) but works AGAINST a row, where tension is lowest at the fully contracted position that is hardest. Band suitability is pattern-dependent, not global - pushing patterns fit, pulling patterns do not.','mechanistic','moderate',NULL,'Biolayne (Norton) - Resistance Bands Better than Free Weights?'),
  ('equipment','band_eccentric_and_stretch_tension_loss','Bands can go slack during the eccentric phase, producing little loading in the lowering portion, and often give minimal tension in the stretched position - two mechanical shortfalls versus free weights, both relevant given the emphasis elsewhere on stretch-position loading.','mechanistic','moderate',NULL,'House of Hypertrophy - The BEST Training Mode for Muscle Growth'),
  ('equipment','band_absolute_resistance_magnitudes','Measured band loads reported by a strength coach: heavier loop bands ~30-40 lb of resistance, lighter bands ~12-15 lb - he states plainly this is not equivalent to weight-room loading. Useful concrete numbers for estimating whether a band prescription can hit a target load.','opinion','weak','{"note": "30-40 lb heavy loop band; 12-15 lb light band"}'::jsonb,'Garage Strength (Miller) - Upper Body BAND PUMP Workout'),
  ('equipment','bands_are_maintenance_not_overload','Two sources independently frame band-only training as maintenance rather than progression: Garage Strength calls its band session ''not super super challenging'' and programs 20-30 rep full-body sets, 15-30 per side for split squats/rows, 25-30 for arm finishers across 4-5 sets; a Westside-affiliated coach says a portable band system ''doesn''t replace training'' but preserves intent for travelling athletes. Band-only blocks should be labelled maintenance in an app, not progression.','practice','moderate','{"note": "20-30 reps; 15-30/side; 25-30 reps; 4-5 sets"}'::jsonb,'Garage Strength; Westside Barbell (conjugate)'),
  ('equipment','bands_bodyweight_minimum_kit','A Stronger By Science host states a basic band set plus bodyweight is enough to train most major muscle groups in 20-30 minutes a day, and points to an SBS article listing band/bodyweight substitutes per muscle group.','practice','moderate','{"note": "20-30 minutes/day"}'::jsonb,'Stronger By Science - Episode 60'),
  ('equipment','minimum_kit_starting_point','A bodybuilding coach''s tiered home-gym recommendation: entry tier = a pair of (ideally adjustable) dumbbells plus an adjustable utility bench; next tier with more budget/space = squat rack, barbell, plates for the loading capacity experienced lifters need. Next priority after that is a pull-up bar or rack-mounted vertical pulley; if that''s out of budget, overhead-anchored bands for band-assisted pull-ups.','practice','moderate',NULL,'3DMuscleJourney - Bodybuilding Home Gym Setup'),
  ('equipment','home_gym_starter_kit_athletic','CONTESTED KIT LISTS: 3DMJ''s minimum is dumbbells + adjustable bench (barbell/rack as a second tier); Garage Strength''s list for an in-season athlete is bumper plates, barbell, squat rack, dip rack, and pull-up bar, covering squats, single-leg squats, bench, cleans/hang cleans, snatch variants, dips, and pull-ups. The divergence is goal-driven - hypertrophy-minimal vs athletic/Olympic-lift coverage - so any ''recommended kit'' feature must branch on goal.','opinion','weak',NULL,'3DMuscleJourney; Garage Strength (Miller)'),
  ('equipment','hypertrophy_achievable_minimal_equipment','Citing Eric Helms, a coach states hypertrophy is still achievable with dumbbells alone provided intensity is appropriate for the rep range used - the qualifier (proximity to failure at the rep range in use) is the operative condition, not the equipment.','opinion','moderate',NULL,'3DMuscleJourney - Bodybuilding Home Gym Setup'),
  ('equipment','flywheel_equivalence','Studies directly comparing flywheel resistance training to conventional weight training find similar strength gains and similar hypertrophy; an earlier meta-analysis claiming flywheel superiority was flawed because it pooled studies comparing flywheel to no training at all rather than to conventional training.','meta-analysis','strong',NULL,'Stronger By Science (Trexler) - Episode 48'),
  ('equipment','flywheel_pattern_coverage','Flywheel devices cover hinge (deadlift/RDL) via a handle attachment, squat via a harness that feels like a belt squat, and rows and biceps straightforwardly; pressing and triceps require improvisation and overall exercise variety is limited versus free weights. Coverage map for a flywheel-equipment profile.','practice','moderate',NULL,'Stronger By Science (Trexler) - Episode 48');

INSERT INTO public.corpus_findings
  (area, topic, claim, basis, confidence, quantities, source)
VALUES
  ('equipment','machine_equivalence_smith','RP coaches note clients often panic when a hotel gym offers only a Smith machine instead of a free rack, but state an effective leg workout is fully achievable on it - consistent with the broader modality-equivalence finding and useful copy for a travel-substitution flow.','practice','moderate',NULL,'Renaissance Periodization - RP Webinar 8-26-2020'),
  ('equipment','quad_isolation_squat_equivalence','A cited study (Kubo et al.) found essentially zero rectus femoris growth from barbell back squat training, attributed to simultaneous hip flexion and knee extension preventing meaningful length change in that muscle. Implication for equipment logic: a squat does not cover rectus femoris, so a knee-extension-pattern slot is needed regardless of squat access.','study','moderate','{"note": "~zero rectus femoris growth"}'::jsonb,'Renaissance Periodization (Israetel) - 6 WILDLY Effective Exercises'),
  ('equipment','quad_stretch_rom_growth','A cited study (Pedro et al.) found leg extensions performed through roughly the bottom half of the range (about 100? to 65? of knee flexion) produced more quadriceps growth at nearly all measured sites than top-half or full-range leg extensions - a partial-ROM prescription that machine-based exercise entries can encode.','study','moderate','{"note": "100? to 65? knee flexion"}'::jsonb,'Renaissance Periodization (Israetel) - 6 WILDLY Effective Exercises'),
  ('equipment','sissy_squat_no_equipment_quad_isolation','The sissy squat is presented as a zero-equipment substitute for a leg-extension machine because it holds the hips extended while flexing the knee through full ROM, versus a typical leg-extension machine reaching only ~100? of knee flexion (one heels-elevated leg-press setup reached 165?). This is the strongest documented bodyweight answer to the knee-extension pattern gap.','mechanistic','moderate','{"note": "~100? machine; 165? heels-elevated leg press"}'::jsonb,'Renaissance Periodization (Israetel) - 6 WILDLY Effective Exercises'),
  ('equipment','lateral_raise_resistance_profile_flip','A single-dumbbell lying side raise (on a bench or floor) inverts the standing lateral raise''s resistance curve: standing loads hardest at the top shortened position with near-zero resistance at the stretch, while lying loads hardest at the lengthened stretched position - achieving a cable-like stretch-biased profile with one dumbbell and no cable or machine.','mechanistic','moderate',NULL,'Renaissance Periodization (Israetel) - 6 WILDLY Effective Exercises'),
  ('equipment','incline_pushup_pec_growth','A cited study comparing 45? incline to flat Smith-machine press found better pec growth at every measured site from the incline, with the advantage growing further up the chest - used to justify feet-elevated push-ups as a no-equipment way to bias upper chest.','study','moderate','{"note": "45? incline"}'::jsonb,'Renaissance Periodization (Israetel) - 6 WILDLY Effective Exercises'),
  ('equipment','pistol_squat_properties','Pistol squats are positioned as the no-rack quad option: substantially less spinal load than high-bar back squats (load = bodyweight plus whatever can be held), ~2 minutes to reach a heavy work set versus ~20 minutes warming up to 3-4 plates/side back squats, and loadable in travel settings (one coach used two 50 lb dumbbells held at the chest in a rackless hotel gym). Caveat: many trainees cannot add any external load to a pistol at all, which is where the lower-body ceiling bites.','opinion','weak','{"note": "~2 min vs ~20 min warm-up; 3-4 plates/side; two 50 lb dumbbells"}'::jsonb,'Renaissance Periodization (Israetel) - 6 WILDLY Effective Exercises'),
  ('equipment','furniture_and_improvised_equipment','Documented improvisations: split squats and pistols off a park bench, kitchen chair, or couch; feet- or hand-elevated push-ups off the same; a partially filled 5-gallon water jug as an adjustable load (about 1/3 full for curls, ~1/2 for overhead press, nearly full for split squats); a towel over an overhead bar or tree branch as a grip substitute. Ordinary furniture, not specialized gear, unlocks most substitutions.','opinion','weak','{"note": "5-gallon jug: ~1/3 curls, ~1/2 overhead press, near-full split squats"}'::jsonb,'3DMuscleJourney; Garage Strength (Miller)'),
  ('equipment','overhead_anchor_is_the_binding_constraint','Multiple sources converge on one hard dependency for zero-equipment upper-body pulling: something to hang from. A low sturdy tree branch or equivalent bar unlocks pull-ups, face pulls, inverted rows, and inverted curls (plus slow-eccentric pull-up practice); without it, pulling coverage collapses to overhead-anchored bands. Treat ''has an overhead anchor'' as a first-class equipment flag, not an exercise attribute.','practice','moderate',NULL,'Renaissance Periodization (Israetel); Garage Strength (Miller); 3DMuscleJourney'),
  ('equipment','bodyweight_press_pattern_substitutes','Vertical press without equipment progresses as bent-knee wall handstand push-ups ? straight-leg ? feet-elevated pike push-ups off a bench; horizontal press via explosive/clap push-ups and feet- or hand-elevated push-ups. A concrete ordered progression an app can encode for the press pattern.','practice','moderate',NULL,'Garage Strength (Miller) - Best Bodyweight Exercises for Athletes'),
  ('equipment','unilateral_volume_prescription_bodyweight','A concrete no-equipment leg session prescription: 4 sets of 7 reps per leg for lateral/cossack squats and 5 reps per leg for reverse lunges. Single-source practitioner programming, not evidence-derived.','opinion','weak','{"note": "4x7/leg cossack; 5 reps/leg reverse lunge"}'::jsonb,'Garage Strength (Miller) - Hotel Bodyweight Workout'),
  ('equipment','pushup_to_bench_transfer_unsupported','CONTESTED AND UNSUPPORTED: Garage Strength claims 50 clap push-ups a day (split as 10x5, 5x10, or 2x25) can carry a raw bench to 315-350 lb and that dips, pull-ups, clap and handstand push-ups done daily mean ''you don''t really need to go to the gym'' for upper-body work - while conceding it stops working around a 500 lb bench. No evidence is offered for the push-up-to-bench relationship, and it sits against the load-progression principle every other source in this corpus states. Do not surface as guidance; the rep-splitting detail is the only usable part.','opinion','weak','{"note": "50 clap push-ups/day; 10x5 / 5x10 / 2x25; claimed 315-350 lb bench; breaks down at 500 lb"}'::jsonb,'Garage Strength (Miller) - How I Bench Pressed 350lbs'),
  ('tempo','tempo_rep_duration_equivalence','When sets are taken to or within ~2-3 reps of failure, total repetition durations from 0.5 s to 8 s produce similar whole-muscle hypertrophy; loads allowing anywhere from ~5-35 reps to failure are likewise similar.','meta-analysis','strong','{"note": "0.5-8 s per rep; 2-3 RIR; 5-35 reps to failure"}'::jsonb,'House of Hypertrophy (Schoenfeld tempo meta-analysis, 4 studies); House of Hypertrophy ''Constant Tension'''),
  ('tempo','eccentric_duration_2_6s_no_difference','A review of 26 repetition-tempo studies found no clear hypertrophy or strength difference across eccentric durations of 2-6 s; a second independently cited review reached the same conclusion.','meta-analysis','strong','{"note": "26 studies; 2-6 s eccentric"}'::jsonb,'Menno Henselmans ''The best repetition tempo''; corroborated by Flow High Performance ''What Rep Speed is Best'''),
  ('tempo','eccentric_duration_threshold_tradeoffs','The same 26-study review found eccentrics under 2 s improved subsequent concentric 1RM, velocity and power relative to eccentrics over 4 s, while eccentrics over 4 s raised time under tension but reduced the total training volume completable.','meta-analysis','strong','{"note": "<2 s vs >4 s eccentric"}'::jsonb,'Menno Henselmans ''The best repetition tempo'''),
  ('tempo','eccentric_slow_vs_fast_contested','CONTESTED: whether a slower eccentric beats a faster one is not settled. A 12-week preacher-curl trial (3x8, 2x/wk) found 4 s eccentrics superior to 1 s for biceps growth, but two other 1 s vs 4 s preacher-curl studies found the same direction non-significant, and a Pearson RCT on leg extensions in strength-trained men found 1 s and 3 s eccentrics produced similar adaptations. Directionally there is a slight trend favouring slower eccentrics with fast concentrics, but the effect does not survive consistently.','study','moderate','{"note": "1 s vs 3 s vs 4 s eccentric; 12 weeks; 3 sets x 8 reps; 2x/week"}'::jsonb,'Flow High Performance ''How Slow Should You Lower the Weight?''; House of Hypertrophy ''Most OVERRATED Muscle Building Principle''; Menno Henselmans'),
  ('tempo','eccentric_2s_vs_4s_no_significant_difference','An 8-week within-subject leg-extension trial (10 untrained adults, 5 sets to failure at 70% 1RM, 2x/week, 1 s concentric) found the 4 s eccentric leg gained marginally more quad thickness than the 2 s leg, but the difference was not statistically significant and there was no consistent per-muscle trend.','study','moderate','{"note": "10 subjects; 8 weeks; 5 sets; 70% 1RM; 2 s vs 4 s eccentric"}'::jsonb,'Flow High Performance ''How Slow Should You Lower the Weight?'' / ''What Rep Speed is Best'''),
  ('tempo','super_slow_tempo_inferior','Deliberately super-slow tempos do underperform: a 6-week trial in 34 untrained women (3x6-10, 2x/wk) found greater quad CSA growth with a 1-2 s concentric/eccentric than with a 10 s concentric + 4 s eccentric, and a separate study found 10 s/4 s at 40-60% 1RM produced inferior muscle-fibre growth than 1-2 s tempo at 80-85% 1RM despite both training close to failure.','study','moderate','{"note": "34 women; 6 weeks; 10 s concentric + 4 s eccentric at 40-60% 1RM vs 1-2 s at 80-85% 1RM"}'::jsonb,'Flow High Performance ''What Rep Speed is Best''; House of Hypertrophy ''Most OVERRATED'''),
  ('tempo','tut_practical_bounds','Time under tension appears to have wide usable bounds rather than an optimum: ~9 s per set (7 sets of 3) matched 3 sets of 10 for hypertrophy at the low end, while an estimated 84-140 s per set from a super-slow protocol was inferior at the high end - so roughly 9 s to ~85 s per set is the range where TUT does not appear limiting.','study','moderate','{"note": "~9 s/set (7x3) vs 3x10; 84-140 s/set super-slow"}'::jsonb,'House of Hypertrophy ''Most OVERRATED Muscle Building Principle'''),
  ('tempo','tut_not_a_predictor','Time under tension is not a strong independent predictor of hypertrophy: in the 2 s vs 4 s eccentric leg-extension trial the 4 s group accumulated nearly double the TUT without anything close to double the growth.','study','moderate','{"note": "~2x TUT, no proportional growth difference"}'::jsonb,'Flow High Performance ''How Slow Should You Lower the Weight?'''),
  ('tempo','concentric_tempo_not_prescribable','Concentric tempo cannot be meaningfully prescribed as a duration: rep speed slows involuntarily as fatigue accumulates within a set regardless of intent, so only the first few reps are actually under the lifter''s control. Only the eccentric phase is realistically prescribable.','practice','moderate',NULL,'Flow High Performance ''Lifting Technique: Does it Really Matter?'' / ''What Tempo is Best'''),
  ('tempo','concentric_intent_fast_for_strength','Concentric speed does not appear to affect hypertrophy on its own, but there is near-universal agreement across sources that intending to move the load explosively is best for strength and power; a faster tempo also allows more load or more reps, which benefits strength goals without directly benefiting size.','practice','moderate',NULL,'Flow High Performance; Menno Henselmans'),
  ('tempo','eccentric_control_is_not_slowness','A meta-analysis found concentric and eccentric actions are both effective for growth, so the standard ''control the eccentric'' coaching cue is about the muscle actively doing the work rather than gravity dropping the weight - it is not an instruction to slow the rep down.','meta-analysis','strong',NULL,'Flow High Performance ''Technique for Maximal Muscle Hypertrophy'''),
  ('tempo','eccentric_overload_is_load_not_tempo','Studies showing eccentric-only training superior to concentric-only are attributed to the heavier loads eccentric groups can use, not to tempo; true eccentric overload requires roughly 20% and often 50% more load than can be lifted concentrically before hypertrophy differences appear.','mechanistic','moderate','{"note": "minimum ~20%, often 50% above concentric capacity"}'::jsonb,'Menno Henselmans ''The best repetition tempo'''),
  ('tempo','stretch_reflex_cost_of_slow_eccentrics','Deliberately slowing the eccentric forfeits the stretch reflex (nervous-system potentiation of the concentric following a fast stretch), which is a mechanistic reason slower eccentrics reduce the reps completable at a given load.','mechanistic','moderate',NULL,'Menno Henselmans ''The best repetition tempo''');

INSERT INTO public.corpus_findings
  (area, topic, claim, basis, confidence, quantities, source)
VALUES
  ('tempo','slow_eccentric_compound_limiter','Very slow eccentrics on free-weight compounds (e.g. an 8 s squat eccentric) risk ending the set on cardiorespiratory or stabiliser fatigue before the target muscle reaches failure - a limitation machine isolation work does not have.','practice','weak','{"note": "8 s eccentric on squat"}'::jsonb,'Flow High Performance ''How Slow Should You Lower the Weight?'''),
  ('tempo','tempo_units_couple_to_rom','Because range of motion differs by exercise, the same rep speed yields different eccentric durations across lifts (illustratively ~3 s for a full-depth back squat vs ~2 s for a preacher curl), so a single universal tempo number does not translate cleanly across an exercise catalogue - tempo must be stored per-exercise or expressed as a cue.','practice','moderate','{"note": "~3 s (squat) vs ~2 s (preacher curl), illustrative"}'::jsonb,'Flow High Performance ''How Slow Should You Lower the Weight?'''),
  ('tempo','tempo_regional_effects_inconsistent','CONTESTED and directionally inconsistent: tempo may shift where in a muscle growth occurs, but studies disagree on direction. Denis (44 untrained women, 10 wk, 6 reps at 50% 1RM, 3x/wk) found both 5s/1s and 1s/5s tempos grew rectus femoris more at 50% thigh length than 3s/3s; Pearson (13 well-trained men, 8 wk, 1s/1s vs 1s/3s) found the FASTER eccentric leg grew more at 60% thigh length; another leg-extension study found a 1 s eccentric grew the distal quad more than 3 s. Sources caution these are small single studies needing replication.','study','weak','{"note": "44 women, 10 wk, tempos 5/1, 1/5, 3/3; 13 men, 8 wk, 1/1 vs 1/3; 1 s vs 3 s eccentric"}'::jsonb,'House of Hypertrophy ''Can Repetition Tempo Impact Regional Muscle Growth?''; Flow High Performance'),
  ('tempo','slow_light_matches_fast_heavy','Tanimoto et al. found a 3 s up / 3 s down no-pause tempo at 50-60% 1RM produced hypertrophy statistically similar to 1s/1s/1s-pause at 85-90% 1RM across chest, biceps, triceps, abs, quads and hamstrings in 24 untrained men (both ~8 reps to failure), and replicated the result for leg-extension quad CSA in 16 men over 12 weeks at 50% vs 80% 1RM.','study','moderate','{"note": "24 men and 16 men; 50-60% vs 85-90% 1RM; 3s/3s vs 1s/1s/1s; 12 weeks"}'::jsonb,'House of Hypertrophy ''Is Constant Tension the Key?'''),
  ('tempo','tempo_prescribability_verdict','ENGINEERING VERDICT: no single numeric tempo prescription is supported. Hypertrophy is comparable across essentially the whole practical range (0.5-8 s per rep, 2-6 s eccentric, ~9 to ~85 s TUT per set) once training is close to failure. Tempo is better modelled as a coaching cue (control the lowering, brief pause at stretch) than as a prescribed number with a proven optimum. Range of motion has more specific numeric evidence than tempo does.','meta-analysis','strong','{"note": "0.5-8 s/rep; 2-6 s eccentric; ~9-85 s TUT"}'::jsonb,'Menno Henselmans; Flow High Performance; House of Hypertrophy (synthesis)'),
  ('tempo','pause_no_direct_evidence','There is no direct research on how intra-rep isometric pauses (bottom, top, or mid) affect hypertrophy. A 1-2 s pause in the stretched position is an indirect inference from loaded-stretch research, and even proponents expect any effect to be very small.','opinion','weak','{"note": "1-2 s pause suggested, no evidence base"}'::jsonb,'Flow High Performance ''Lifting Tempo''; ''What Rep Speed is Best''; Stronger By Science'),
  ('tempo','pause_extends_set','A passive pause in a low-tension position near failure lets a lifter extend a set by a few reps; this is the mechanism underlying rest-pause, cluster sets and myo-reps, used mainly to compress session time rather than to add a distinct hypertrophy stimulus.','practice','moderate',NULL,'Flow High Performance ''Lifting Tempo'' / ''What Rep Speed is Best'''),
  ('tempo','stretch_shortening_cycle_hypothesis','Controlling the eccentric to the bottom without bouncing is advised on the hypothesis that the stretch-shortening cycle uses elastic tendon recoil rather than active muscle tension and shortens time in the most-stretched (most hypertrophic) position - but there is no direct evidence on SSC and hypertrophy. A pause at the bottom is also claimed to reduce strain risk.','opinion','weak',NULL,'Flow High Performance; Renaissance Periodization'),
  ('tempo','isometric_long_length_matches_full_rom','In a 6-week within-subject trial (Varovic/Wolf/Schoenfeld et al., 23 resistance-trained participants, 2x/week), a leg trained with isometric holds at the most stretched knee-extension position grew its quadriceps about the same amount as the leg trained with full-ROM dynamic leg extensions.','study','moderate','{"note": "23 trained participants; 2x/week; 6 weeks"}'::jsonb,'Renaissance Periodization ''Have I Been Undervaluing Isometrics?'''),
  ('tempo','isometric_long_vs_short_length','Isometric training at long muscle lengths produces more hypertrophy than at short muscle lengths - a 2019 Oranchuk systematic review of 9 studies found considerably greater growth at long lengths, and a separate tally of 5 isometric studies agreed.','meta-analysis','strong','{"note": "9 studies (Oranchuk 2019); 5 studies (separate tally)"}'::jsonb,'Stronger By Science; House of Hypertrophy'),
  ('tempo','isometric_regional_dependence','Isometric holds are position-dependent for regional growth: short-length holds bias the proximal end of the fibres, long-length holds bias the distal end, with no single position growing the muscle evenly. This parallels a 2017 Franchi review reporting eccentric training biases distal growth and lengthens the muscle belly while concentric training adds width mid-belly.','mechanistic','moderate',NULL,'Renaissance Periodization ''Have I Been Undervaluing Isometrics?'''),
  ('tempo','isometric_practical_drawbacks','Practical cautions for isometrics (opinion, not evidence): true failure is hard to identify without bar speed as a cue, and isometric contractions are claimed to drive more CNS fatigue per set than dynamic work, making heavy isometric use less sustainable across a block. One suggested finisher holds ~half an inch above full stretch to failure and adds +5 s, then +10 s, then +15 s across successive weeks.','opinion','weak','{"note": "+5 s, +10 s, +15 s across weeks; ~0.5 inch above full stretch"}'::jsonb,'Renaissance Periodization ''Have I Been Undervaluing Isometrics?'''),
  ('tempo','rom_full_vs_partial_meta_trivial','A 2023 Wolf et al. meta-analysis found that when partial ROM is treated as one undifferentiated category, full ROM produced better hypertrophy AND better strength/power/sport outcomes than partial - but in both cases the effect size was statistically trivial.','meta-analysis','strong','{"note": "2023 meta-analysis; trivial effect sizes"}'::jsonb,'Stronger By Science ''What Is The BEST Range of Motion?'''),
  ('tempo','rom_shortened_partial_inferior','Across 10 studies comparing shortened-position partials to full ROM or lengthened partials, overall growth was generally somewhat worse with shortened partials - though shortened partials still produced meaningful growth. Shortened partials were never found superior to full ROM.','meta-analysis','strong','{"note": "10 studies"}'::jsonb,'House of Hypertrophy ''Faster Muscle Growth''; Biolayne'),
  ('tempo','rom_lengthened_beats_shortened_partial','Across 8 studies comparing the same partial ROM trained at long vs short muscle length, 7 favoured the lengthened partial and 1 found no difference; none favoured the shortened partial. McMahon''s knee-extension study (90-40 deg vs 50-0 deg) found greater vastus lateralis CSA at every measured region for the long-length group, and Sato''s preacher-curl study found the long-length partial group averaged 2.6x more elbow-flexor hypertrophy across sites at 50/60/70% humerus length.','meta-analysis','strong','{"note": "8 studies (7/1/0); 90-40 vs 50-0 deg knee flexion; 2.6x elbow-flexor growth"}'::jsonb,'Jeff Nippard; House of Hypertrophy; Stronger By Science'),
  ('tempo','rom_lengthened_partial_vs_full_contested','CONTESTED - sources disagree on both the tally and the conclusion for lengthened partials vs FULL ROM. Jeff Nippard cites 5 studies (4 favouring lengthened partials, 1 no difference, 0 favouring full ROM). Stronger By Science cites only 3 direct comparisons at the time of the 2023 meta-analysis, broadly favouring lengthened partials but flagged as too few. House of Hypertrophy cites 6 studies split by training status. Separately, two channels give conflicting tallies for what both call ''the 6 full-vs-partial studies'': Flow says 5 favoured full ROM and 1 favoured partial, House of Hypertrophy says 4 full / 1 null / 1 partial. Treat ''lengthened partials beat full ROM'' as unresolved.','meta-analysis','moderate','{"note": "3, 5, or 6 studies depending on source; tallies 4/1/0, 5/1, 4/1/1"}'::jsonb,'Jeff Nippard; Stronger By Science; House of Hypertrophy; Flow High Performance'),
  ('tempo','rom_trained_vs_untrained_divergence','Training status appears to moderate the lengthened-partial effect: all 3 studies in untrained subjects found more hypertrophy with lengthened partials, while the 3 in trained subjects showed similar mid-region growth. Two larger trained-lifter studies (n=25 upper-body program; n=297 full-body program) found no significant advantage for lengthened partials on biceps, triceps, arm or thigh growth.','meta-analysis','moderate','{"note": "3 untrained + 3 trained studies; n=25 and n=297 trained cohorts"}'::jsonb,'House of Hypertrophy ''Faster Muscle Growth'' / ''Training BEYOND Failure'''),
  ('tempo','llp_expected_effect_size','Researcher Dr. Milo Wolf''s own estimate of the upside from swapping full ROM for long-length partials is roughly 5-10% more muscle growth - an expert estimate, not a measured pooled effect.','opinion','weak','{"note": "5-10% improvement"}'::jsonb,'Jeff Nippard ''The World''s Smartest Muscle Building Technique'''),
  ('tempo','llp_operational_definition_and_errors','Studied lengthened-partial protocols are operationally ''half reps'' - the bottom half of the ROM, from most-stretched to the halfway point - so the technique is expressible as a ROM fraction, not a subjective cue. The two common execution errors are letting form loosen (partials still require a controlled negative and minimal momentum) and under-cutting the range, i.e. actually performing ~90% of full ROM instead of a true half. One presenter also suggests a 1-2 month gradual transition rather than an abrupt switch.','practice','moderate','{"note": "bottom 50% of ROM; ~90% is the common mistake; 1-2 month transition"}'::jsonb,'Stronger By Science; Jeff Nippard'),
  ('tempo','llp_post_failure_intensity_technique','Long-length partials can be used as an end-of-set extension: after full-ROM failure on lifts like lat pulldowns, rows or hamstring curls, continuing with stretched-position partials typically yields roughly 3-6 additional reps.','opinion','weak','{"note": "3-6 additional partial reps"}'::jsonb,'Jeff Nippard ''The World''s Smartest Muscle Building Technique'''),
  ('tempo','post_failure_partials_evidence','CONTESTED by training status: in untrained subjects, continuing calf raises past full-ROM failure with lengthened partials produced 43.3% greater relative medial gastrocnemius growth than stopping at full-ROM failure. But in a direct 8-week trial with 23 trained lifters (7.3 yrs experience, 4 sets, 2x/wk), pure lengthened partials only trended above full ROM + post-failure partials, with weak statistical support and high measurement error.','study','moderate','{"note": "43.3% relative difference (untrained); 23 trained subjects, 7.3 yrs, 4 sets 2x/wk, 8 weeks"}'::jsonb,'House of Hypertrophy ''Training BEYOND Failure'''),
  ('tempo','llp_set_efficiency','Efficiency finding: in a 10-week within-participant calf study in untrained men, one leg did 4-6 sets to failure of full ROM while the other did 2-3 sets of full ROM followed by volume-load-matched lengthened partials; both grew equally, but the partials leg used about half the sets and ~20% fewer total reps.','study','moderate','{"note": "4-6 vs 2-3 sets; ~20% fewer reps; 10 weeks"}'::jsonb,'Biolayne ''Taking Sets Past Failure For Better Gains?'''),
  ('tempo','pedrosa_leg_extension_protocol','Pedrosa et al.: 45 untrained women, 12 weeks, knee extension, 3-6 sets x 7 reps at 60% 1RM, 3x/week, 3 min rest, 2 s up / 2 s down, 1RM retested every 2 weeks, across four groups - long-length partial (100-65 deg knee flexion), short-length partial (65-30 deg), near-full ROM (100-30 deg), and a varied group alternating partials. The long-length partial group had the best overall quad growth (varied group second), and at 70% of femur length its CSA increase exceeded every other group including full ROM. The presenter explicitly cautions this is one study needing replication.','study','moderate','{"note": "45 women; 12 wk; 100-65 / 65-30 / 100-30 deg; 3-6x7 at 60% 1RM; 3x/wk; measured at 40/50/60/70% femur length"}'::jsonb,'House of Hypertrophy ''Full ROM Is NOT Optimal''; Stronger By Science'),
  ('tempo','regional_proximal_distal_rule','A consistent regional pattern across the ROM literature: proximal muscle sites tend to grow similarly regardless of the ROM trained, but training through the long-muscle-length portion - via full ROM or long-length partials - appears necessary to fully grow the distal portion. Where in the ROM you train determines where in the muscle growth happens, not just how much.','mechanistic','moderate',NULL,'Stronger By Science; House of Hypertrophy; Flow High Performance'),
  ('tempo','bench_press_rom_transfer_contested','CONTESTED by population. In a 10-week Smith-machine bench trial (49 men, 6 months experience, 2x/week), full ROM produced the greatest 1RM/bodyweight gains on full, two-thirds AND one-third ROM tests - i.e. full ROM raised partial-range 1RM more than training that partial range did, an apparent violation of specificity. But two Massey et al. studies training only the first 2-5 inches of the bench range found full ROM superior in untrained women while producing full-ROM 1RM gains not statistically different from partial or combined training in men with some experience.','study','moderate','{"note": "49 men; 10 wk; 2x/wk; full vs 2/3 vs 1/3 ROM; Massey first 2-5 inches"}'::jsonb,'House of Hypertrophy ''HALF Bench Press Reps''; ''This is KEY for More Muscle''');

INSERT INTO public.corpus_findings
  (area, topic, claim, basis, confidence, quantities, source)
VALUES
  ('tempo','squat_depth_contested','CONTESTED for the quadriceps. A 10-week trial (17 untrained males, 3x8-10, 2x/wk) found full-depth squats at 140 deg knee flexion slightly superior to 90-deg partials for quad, adductor and glute max growth, with strength gains following specificity in each group. But another study comparing 90 vs 140 deg found quad hypertrophy SIMILAR with only glute max favouring the deeper condition, and a 2019 Japanese study found 90-deg partial squats matched full ROM for quad growth. Bloomquist''s comparison is less ambiguous only because its partial was much shallower: 0-120 deg full ROM beat 0-60 deg partial across many thigh regions.','study','moderate','{"note": "17 untrained males; 10 wk; 140 vs 90 deg knee flexion; Bloomquist 0-120 vs 0-60 deg"}'::jsonb,'Stronger By Science; House of Hypertrophy'),
  ('tempo','lower_body_rom_saturation','Suggestive evidence that lower-body ROM benefit saturates once a moderate stretch is reached: a leg-press study comparing 100 deg vs an average 154 deg of knee flexion found similar regional quad growth, consistent with the finding that 90 deg of knee flexion may already provide sufficient quad stretch.','study','weak','{"note": "100 deg vs avg 154 deg knee flexion"}'::jsonb,'House of Hypertrophy ''Faster Muscle Growth'' / ''This is KEY for More Muscle'''),
  ('tempo','elbow_rom_contested','CONTESTED and directly contradictory for the arms. Goto et al. (44 men, 1+ yr experience, 3x8 skull crushers, 3x/wk, 8 wk) found a partial ROM of 45-90 deg elbow flexion produced significantly greater triceps CSA than full ROM, and a separate study found stretched-position-only skull crushers beat full ROM. Pinto et al. (30 untrained men, preacher curl, 2-4 sets of 8-20, 2x/wk, 10 wk) found the opposite: full ROM (0-130 deg) beat the partial (50-100 deg) for biceps thickness. A systematic review found only 2 studies directly testing partial vs full in arm muscles - 1 each way.','study','moderate','{"note": "Goto 44 men, 45-90 deg, 3x8, 3x/wk, 8 wk; Pinto 30 men, 0-130 vs 50-100 deg, 10 wk; review: 2 arm studies split 1-1"}'::jsonb,'House of Hypertrophy ''Is Constant Tension the Key?''; Flow High Performance ''Range of Motion for Hypertrophy'''),
  ('tempo','preacher_curl_distal_llp_trained','In an 8-week trial of 13 trained individuals (~6 yrs experience, unilateral machine preacher curl, 5x10-15, 2 min rest, 2x/wk), full ROM (0-140 deg elbow flexion) and lengthened partials (0-70 deg) produced similar growth at the 50% muscle region, but lengthened partials produced greater growth at the 70% distal region (Bayes factor 4.87, moderate evidence).','study','moderate','{"note": "13 trained, ~6 yrs; 0-140 vs 0-70 deg; 5x10-15; 8 wk; BF 4.87"}'::jsonb,'House of Hypertrophy ''Faster Muscle Growth: This New Study Is Epic'''),
  ('tempo','calf_standing_vs_seated','In a 12-week study (14 untrained adults, 3-5 sets of 10, 2x/week), standing calf raises - which stretch the gastrocnemius more via knee extension - produced significantly greater lateral and medial gastrocnemius volume gains than seated calf raises, while the soleus grew similarly in both.','study','moderate','{"note": "14 adults; 3-5 sets x 10; 2x/wk; 12 weeks"}'::jsonb,'Flow High Performance ''What Range of Motion Should You Train With?'''),
  ('tempo','calf_rom_comparison','In an 8-week study (42 untrained women, 3 sets of 15-20 to failure, 3x/week), full-ROM calf raises produced significant gastrocnemius thickness gains, lengthened-position partials were MORE effective than full ROM, and shortened-position partials were less effective. A separate untrained calf study reported a 126.9% relative advantage for lengthened partials over full ROM.','study','moderate','{"note": "42 women; 3x15-20; 3x/wk; 8 weeks; 126.9% relative difference in a separate study"}'::jsonb,'Flow High Performance; House of Hypertrophy ''Training BEYOND Failure'''),
  ('tempo','hamstring_seated_vs_lying_curl','A 2021 Japanese study found seated leg curls - which lengthen the two-joint hamstrings more via hip flexion at the same knee ROM - produced superior biceps femoris long head and semitendinosus growth at both upper and lower regions than lying leg curls, while the single-joint biceps femoris short head grew similarly. Exercise selection can therefore change muscle length independently of ROM.','study','moderate','{"note": "2021 study"}'::jsonb,'House of Hypertrophy ''This is KEY for More Muscle''; Flow High Performance'),
  ('tempo','triceps_overhead_vs_pushdown','A 2022 Japanese within-subject study found overhead triceps extensions produced significantly greater long-head growth than pushdowns, and unexpectedly also significantly greater medial and lateral head growth despite those heads not being stretched more in the overhead position.','study','moderate','{"note": "2022 study"}'::jsonb,'House of Hypertrophy ''This is KEY for More Muscle'''),
  ('tempo','quad_activation_by_knee_angle','Quadriceps voluntary activation during maximal contractions averaged 93.6% at 50 deg knee flexion, 96% at 75 deg, and 98.5% at 100 deg - evidence that the muscle can be more fully recruited at longer lengths.','study','moderate','{"note": "93.6% at 50 deg; 96% at 75 deg; 98.5% at 100 deg"}'::jsonb,'House of Hypertrophy ''Full ROM Is NOT Optimal'''),
  ('tempo','stretch_mediated_mechanism_hypothesis','The proposed mechanism for the long-muscle-length advantage combines greater active tension (higher voluntary activation at long lengths) with greater passive tension (titin stretch within sarcomeres), plus the observation that a lift''s sticking point sits near the stretched position where rep speed is slowest and cross-bridge formation is theorised to peak. Every source presenting this frames it as an unconfirmed hypothesis.','mechanistic','weak',NULL,'House of Hypertrophy; Biolayne'),
  ('tempo','loaded_stretch_alone_hypertrophic','In an 8-week study, 81 untrained adults doing intense static pec stretching for 15 minutes 4x/week gained pec thickness similar in magnitude to a separate group doing chest flies for 5 sets of 12, 3x/week - mechanistic evidence that loaded-stretch time alone can be hypertrophic.','study','moderate','{"note": "81 adults; 15 min x 4/wk; 8 weeks; vs 5x12 x 3/wk"}'::jsonb,'Flow High Performance ''What Rep Speed is Best'''),
  ('tempo','rom_strength_specificity','For strength, adaptation is range-specific: the closer training ROM matches the competition/test ROM, the greater the strength gain in that range (powerlifting squat to parallel vs Olympic lifting''s deeper positions). A 2014 study found lockout-position training built strength only near lockout while full ROM built strength across a wider spread of joint angles.','meta-analysis','strong','{"note": "2014 lockout study"}'::jsonb,'Stronger By Science; Biolayne'),
  ('tempo','combining_full_and_partial_for_strength','Combining full ROM with some partial ROM work for strength yields similar or slightly greater full-ROM strength than full ROM alone: across 7 studies gains were similar-or-better for combined training, and 4 controlled studies (Basler 2014, Gillingham & DeBaliso, Pedrosa 2021, Whaley 2020) each nominally favoured the combined group without reaching significance. Basler: 3 full + 3 partial squat sets (to ~80 deg knee flexion) 2x/wk for 7 wk gave +8.2% squat 1RM vs +5.1% for 6 full-ROM sets. Whaley: progressive-ROM pin squats +14.5 kg vs +11 kg full-ROM-only over 7 weeks.','meta-analysis','moderate','{"note": "7 studies; Basler 8.2% vs 5.1%, 7 wk; Whaley 14.5 kg vs 11 kg, 7 wk"}'::jsonb,'Stronger By Science ''Combining ROMs for larger strength gains?'''),
  ('tempo','overload_partials_for_lockout','Short-muscle-length ''overload'' partials (board press, pin press, rack pulls, block pulls) are probably worse than full ROM for hypertrophy but remain useful for strength, and make most sense specifically when the lifter''s sticking point is at the top/lockout of the lift. Layne Norton''s parallel recommendation: the competition squat only needs to break parallel for specificity, while accessory squat variations should still be trained full ROM for the hypertrophy benefit.','practice','moderate',NULL,'Stronger By Science ''Combining ROMs''; Biolayne ''Full ROM vs Partial ROM'''),
  ('tempo','full_rom_recovery_cost','Longer muscle lengths carry a recovery cost: a bicep-curl study found full ROM caused greater soreness, greater strength loss and reduced elbow ROM over the 72 hours post-training than partial ROM, and an isometric biceps study found long-length contractions produced longer strength-recovery time, more soreness and greater tenderness than short-length ones.','study','moderate','{"note": "72 hours post-training"}'::jsonb,'Flow High Performance ''Why Full ROM Training is Best''; ''Range of Motion for Hypertrophy'''),
  ('tempo','rom_flexibility_benefit','Full-ROM resistance training carries a mobility benefit: a meta-analysis found resistance training alone increases joint flexibility about as much as dedicated stretching (both vs no training), and a 12-week study of 24 adults with chronic low back pain found full-ROM machine back extensions improved total lumbar ROM more than partial ROM.','meta-analysis','moderate','{"note": "24 adults; 12 weeks"}'::jsonb,'Flow High Performance ''What Range of Motion Should You Train With?'''),
  ('tempo','rom_upper_limit_caution','ROM can be taken too far. Reduced ROM is preferable when full ROM causes joint or connective-tissue pain from prior injury or anatomy, or when the range becomes so extreme that tension leaves the target muscle - cited examples are overly deep dips (stress shifting to shoulder/scapula) and squatting deep enough to flex the spine. No numeric depth threshold is given by any source.','practice','moderate','{"note": "no threshold given"}'::jsonb,'Flow High Performance ''Range of Motion | Technique for Hypertrophy Training''; ''Technique for Maximal Muscle Hypertrophy'''),
  ('tempo','stretch_evidence_coverage_by_muscle','Coverage is uneven by muscle. Lengthened-position benefit has direct study support for quadriceps, glutes, adductors, two-joint hamstrings, biceps, triceps and calves, but no published research yet for back, shoulders, abs or chest. The lower-body evidence also comes from movements where the stretched position is the mechanically weakest point (squat, leg press) - it is unclear whether the same holds for shoulder raises, rows or pulldowns where the stretched position is the strongest point. A 2020 study claiming squats beat hip thrusts for glutes should not be used as stretch-mechanism evidence, as that research group''s data validity has been publicly questioned.','study','moderate',NULL,'House of Hypertrophy ''This is KEY for More Muscle''; Biolayne ''The Partial ROM Debate'''),
  ('tempo','technique_effects_are_small_near_failure','When training close to failure, technique variables - ROM, tempo, strictness - appear to have only a small overall influence on hypertrophy compared with proximity to failure and total volume. The one study directly testing strictness found biceps curls and triceps pushdowns performed strictly vs with allowed momentum produced similar muscle thickness gains.','practice','moderate',NULL,'Flow High Performance ''Lifting Technique: Does it Really Matter?'''),
  ('tempo','load_range_equivalence','Loads from 30% to 80% 1RM are similarly effective for hypertrophy provided sets go close to failure (30% 1RM typically allows 30-40 reps, 80% allows 7-12). Heavier loads carry costs: greater joint stress, greater cardiorespiratory demand limiting proximity to failure, and longer required rest reducing total sets per session.','study','strong','{"note": "30-80% 1RM; 30-40 reps vs 7-12 reps"}'::jsonb,'House of Hypertrophy ''Most OVERRATED''; Flow High Performance'),
  ('tempo','drop_sets_isolation_vs_compound','Drop sets (reps to failure, then cut load 15-25% and repeat, typically 1-3 drops) show a benefit on ISOLATION work but not compounds. Fink: one triceps-pushdown drop set (12RM plus three ~20% drops) 2x/wk for 6 wk beat three straight sets to failure; Vorovich: drop-set leg was equal overall but grew more at the 30% and 50% rectus femoris sites; Ocasio: one dumbbell-curl drop set matched three straight sets at 80% or 30% 1RM. Two studies using leg press/squat/leg extension in lifters with 2-4+ years experience found no advantage. Only 5 drop-set hypertrophy studies exist in total.','study','moderate','{"note": "15-25% drops, 1-3 drops; Fink 12RM + 3x20% drops, 2x/wk, 6 wk; Ocasio 80/65/50/40/30% 1RM, 8 wk; 5 studies total"}'::jsonb,'House of Hypertrophy ''The Science of Drop Sets'''),
  ('tempo','exercise_variation_regional_bias','Small execution variables can bias regional growth independent of tempo or ROM: a calf-raise study found feet-out increased medial gastrocnemius thickness more, feet-in increased lateral gastrocnemius more, and feet-forward gave roughly equal gains.','study','moderate',NULL,'Flow High Performance ''Lifting Technique: Does it Really Matter?'''),
  ('olympic','corpus_source_bias','CORPUS CAVEAT: roughly 90% of this area''s claims come from a single YouTube channel (Garage Strength / Dane Miller), with only two independent voices (Juggernaut Training Systems, and Dr. Sergii Putsov interviewed on the same channel). Convergence between claims should therefore NOT be treated as independent corroboration, and the cited studies are all secondhand relays by a coach with a commercial stake in Olympic lifting.','corpus-level observation','strong','{"note": "~90% single-source"}'::jsonb,'meta-observation across all olympic-area transcripts'),
  ('olympic','meta_analysis_vertical_jump','A meta-analysis relayed in the corpus (attributed to Hackett and Davies; six studies, 230+ participants, interventions >6 weeks, each requiring at least one Olympic-weightlifting exercise plus a comparison group) reported vertical jump improvements of 7.7% vs non-training control and 5.1% vs traditional resistance training, with no significant difference vs plyometric training. Secondhand citation; may overlap with the systematic review below, so treat as one result, not two.','meta-analysis (secondhand)','moderate','{"note": "6 studies; 230+ participants; >6wk; +7.7% vs control; +5.1% vs traditional RT; ns vs plyometrics"}'::jsonb,'Garage Strength - Why Olympic Lifters Have HUGE Vertical Jumps'),
  ('olympic','systematic_review_vs_traditional_training','A systematic review of 16 studies / 427 participants (relayed in-video) found weightlifting training produced greater gains in load lifted and countermovement jump (analyzed in 9 of the studies) than traditional resistance training, a large effect on linear sprint speed, NO significant advantage for change-of-direction performance, and gains similar to plyometric training for speed, power, and strength.','systematic review (secondhand)','moderate','{"note": "16 studies; 427 participants; CMJ in 9 studies"}'::jsonb,'Garage Strength - The INSANE effects Olympic Lifting has on the Body!');

INSERT INTO public.corpus_findings
  (area, topic, claim, basis, confidence, quantities, source)
VALUES
  ('olympic','catch_versus_pull_only_derivatives','CONTESTED. A cited 10-week study of 27 resistance-trained men found full catch-based Olympic lifting beat pull-only (no-catch) derivatives with moderate-to-large effects on isometric mid-thigh pull, 10/20/30m sprints, and one direction of a 5-10-5 change-of-direction test. The same coach nevertheless asserts pull-only derivatives still train hamstrings, quads, and back adequately - an opinion that runs against the study he cites. Note the change-of-direction result also conflicts with the 16-study systematic review, which found no CoD advantage.','study (secondhand) vs coach opinion','moderate','{"note": "27 men; 10 weeks"}'::jsonb,'Garage Strength - The INSANE effects Olympic Lifting has on the Body!'),
  ('olympic','youth_added_weightlifting_marginal','A cited 28-week study of 59 adolescent male athletes aged 12-14 compared resistance training + plyometrics WITH versus WITHOUT added weightlifting movements and found both groups made only small-to-moderate improvements in countermovement jump, horizontal jump, and 10/20/30m sprint - i.e. adding weightlifting produced little additional benefit in this population. This is the strongest counterweight in the corpus to the general pro-transfer narrative.','study (secondhand)','moderate','{"note": "59 participants; ages 12-14; 28 weeks"}'::jsonb,'Garage Strength - The INSANE effects Olympic Lifting has on the Body!'),
  ('olympic','elite_16week_adaptation_profile','A cited study of 6 male Olympic weightlifters (mean age 23, 88 kg body mass, 146 kg snatch) found that over 16 weeks front squat strength and countermovement jump power rose significantly and leg-press rate of force development improved in the 0-200ms and 0-250ms windows, while muscle architecture and lean body mass did NOT change - adaptation in trained lifters is neural/force-rate, not hypertrophic.','study (secondhand)','moderate','{"note": "n=6; age 23; 88 kg; snatch 146 kg; 16 weeks; RFD 0-200ms and 0-250ms"}'::jsonb,'Garage Strength - The INSANE effects Olympic Lifting has on the Body!'),
  ('olympic','lean_mass_correlates_with_performance','A May 2020 study of 8 well-trained female weightlifters found lean body mass closely correlated with weightlifting performance, consistent with prior reports in young and senior elite male lifters. n=8 is very small - treat as directional only.','study (secondhand)','weak','{"note": "n=8 female weightlifters"}'::jsonb,'Garage Strength - The INSANE effects Olympic Lifting has on the Body!'),
  ('olympic','diminishing_returns_by_training_level','Coaches in the corpus temper the transfer case in two ways: non-elite athletes get their largest vertical-jump response when they FIRST add weightlifting derivatives, while already-elite athletes hit diminishing returns from further snatch/clean load; and one coach explicitly says an athlete''s 39-inch vertical was genetic, not produced by his squats, snatches, or cleans. Useful counter-programming against attributing all power gains to the lifts.','practice + opinion','moderate','{"note": "39-inch vertical cited as genetic"}'::jsonb,'Garage Strength - Why Olympic Lifters Have HUGE Vertical Jumps; The PERFECT Workout For Olympic Weightlifting'),
  ('olympic','derivative_case_study_vertical','Single coach-reported case: a college football player''s vertical jump went from 28 in to 34.5 in over a 72-day pre-draft block built around BOX SNATCHES and CLEAN PULLS rather than the full competition snatch or clean. n=1, uncontrolled, pre-draft context - not a dose-response basis.','practice (n=1)','weak','{"note": "28 in ? 34.5 in over 72 days"}'::jsonb,'Garage Strength - Why Olympic Lifters Have HUGE Vertical Jumps'),
  ('olympic','back_squat_derived_clean_ratios','Rule-of-thumb strength ratios usable as app diagnostics: full clean ? 80% of best back squat; power clean ? 60% of best back squat. A power clean measured at 70% of back squat is flagged as needing more top-end strength work (relatively too weak a squat / too technically efficient a clean).','practice (heuristic, uncited)','weak','{"note": "clean = 80% BS; power clean = 60% BS; 70% flagged as mismatch"}'::jsonb,'Garage Strength - Do This To Power Clean 225 Pounds'),
  ('olympic','front_squat_rep_max_clean_estimate','Complementary heuristic: a 5-rep front squat max approximates an athlete''s full clean; an 8-to-10-rep front squat max approximates their power clean. Uncited coach heuristic, but directly implementable as an estimator when a lifter has front squat data but no clean 1RM.','opinion (heuristic)','weak','{"note": "5RM front squat ? full clean; 8-10RM front squat ? power clean"}'::jsonb,'Garage Strength - Do This To Power Clean 225 Pounds'),
  ('olympic','bodyweight_ratio_targets','Suggested bodyweight-ratio targets treated as ''sufficient'' long-term goals for non-weightlifting athletes rather than something to keep chasing: snatch 1.2x BW (men) / 1.1x BW (women); clean 1.6x BW (men) / 1.4x BW (women). A separate claim in the same corpus sets field-sport athletes (football, throws, heavier wrestlers) at power cleaning at or above bodyweight.','opinion','weak','{"note": "snatch 1.2x/1.1x BW; clean 1.6x/1.4x BW; power clean ? 1.0x BW for field sports"}'::jsonb,'Garage Strength - Why Olympic Lifters Have HUGE Vertical Jumps; The ONLY Olympic Weightlifting Program You''ll Ever Need'),
  ('olympic','power_variant_definition','A power snatch or power clean is operationally defined as catching the bar with the hip joint at 90 degrees or higher relative to the knee (''91 degrees or higher''), distinguishing it from a full-depth squat catch. Gives an app a checkable definition for classifying a logged lift.','practice','weak','{"note": "hip at 91 degrees or higher"}'::jsonb,'Garage Strength - How To Use The Power Snatch And Power Clean In Training'),
  ('olympic','power_variant_technique_standard','Power variants should be coached with the same technical execution as the full lift - knees clearing back off the floor, knees reciprocating forward through the transition, strong finish, flat-footed catch - NOT a wide sprawled receiving stance, which is claimed not to carry over to the full lift.','practice','weak',NULL,'Garage Strength - How To Use The Power Snatch And Power Clean In Training'),
  ('olympic','power_variant_use_by_level','Power variants are prescribed differently by level: for novice/intermediate lifters to build bar acceleration off the hip, tighter catch positions, and dynamic trunk control; for advanced lifters (>3-4 years training) as a deload from intensity/volume, since the lighter catch load spares the lifter while still training bar speed and connection.','practice','weak','{"note": "advanced = more than 3-4 years training"}'::jsonb,'Garage Strength - How To Use The Power Snatch And Power Clean In Training'),
  ('olympic','power_to_full_complex','For advanced lifters, complex of two power cleans into one full clean (or two power snatches into one full snatch) is prescribed to improve bar speed and connection with carryover to the competition lift.','practice','weak','{"note": "2 power reps + 1 full rep per set"}'::jsonb,'Garage Strength - How To Use The Power Snatch And Power Clean In Training'),
  ('olympic','no_feet_variation','The ''no-feet'' power clean and no-feet snatch (feet forbidden to leave the receiving stance) are used as a beginner entry drill: they force a longer force-application period, keep the torso vertical, and stop the athlete learning to jump backward or lose bar contact. Programmed for 6 to 8 weeks within a block.','practice','moderate','{"note": "6 to 8 weeks"}'::jsonb,'Garage Strength - Do This To Power Clean 225 Pounds; How To Snatch Like Lasha Talakhadze'),
  ('olympic','low_hang_variants','Low-hang variants (bar paused just below the kneecap) serve two stated purposes: training the knee-to-hip transition one coach calls ''no man''s land'' - the position where he says most lifters technically lose the bar - and building eccentric hamstring and lower-back strength, especially for quad-dominant athletes. Sequenced after the no-feet variation and before box work.','practice','moderate',NULL,'Garage Strength - Do This To Power Clean 225 Pounds; How To Snatch Like Lasha Talakhadze'),
  ('olympic','high_hang_power_position','The high-hang / power-position snatch (bar starting at the hip crease with slight knee bend) is used to overload the strongest, most powerful extension position of the pull while removing the technical demand of pulling from the floor.','practice','moderate',NULL,'Garage Strength - How To Snatch Like Lasha Talakhadze'),
  ('olympic','muscle_snatch_purpose','The muscle snatch - no re-bend of the knees, no squat catch - isolates upper-body pulling and overhead lockout strength (traps, upper back) from the leg drive and catch. A variant with a slow ~1-2 count eccentric lowering, load light enough not to contact the hips, is prescribed 2 days/week for 4-5 sets of 3-4 reps to train shoulder external rotation and triceps/deltoid strength.','practice','moderate','{"note": "2 days/week, 4-5 sets x 3-4 reps, 1-2 count eccentric"}'::jsonb,'Garage Strength - How To Snatch Like Lasha Talakhadze; Top 4 Explosive Olympic Weightlifting Upper Body Exercises For Athletes'),
  ('olympic','two_box_clean_prescription','The two-box clean/power clean (boxes ~7 in each, bar ~14 in off the floor, near mid-thigh) is prescribed at 4-7 sets of 2-4 reps. Rationale: a static dead-stop start with tension already on the bar matches the no-countermovement demand of a sprint block start, which a hang clean''s eccentric dip does not replicate; it is also a lower-fatigue speed variation for younger athletes struggling with hip contact, and a way for advanced lifters to add load without the recovery cost of pulling from the floor.','practice + mechanistic','moderate','{"note": "~7 in per box (~14 in bar height); 4-7 sets x 2-4 reps"}'::jsonb,'Garage Strength - Top 4 Weightlifting Exercises For Sprinting; The ONLY Olympic Weightlifting Program You''ll Ever Need'),
  ('olympic','dumbbell_drop_snatch_prescription','Dumbbell drop-snatch-to-box, presented as a low-technical-demand ''reflexive'' force-absorption drill: 5-6 sets of 3 reps each side, 20-30 lb dumbbells, box 12-18 in high (12 in called sufficient).','practice','weak','{"note": "5-6 sets x 3 per side; 20-30 lb DB; box 12-18 in"}'::jsonb,'Garage Strength - Top 4 Weightlifting Exercises For Sprinting'),
  ('olympic','pause_snatch_nervous_system_cost','A pause-below-the-knee power snatch initiated on an auditory start cue is capped at ONCE per week, 5 sets of 2 reps, with an explicit warning that the reactive/competitive nature of the drill taxes the nervous system if done more often. One of the few explicit frequency ceilings in the corpus.','practice','moderate','{"note": "1x/week, 5 sets x 2 reps"}'::jsonb,'Garage Strength - Top 4 Weightlifting Exercises For Sprinting'),
  ('olympic','snatch_pull_frequency','The snatch pull - a heavier pull through the full range with no catch - is prescribed once per week as an accessory to reinforce position and force application from the floor.','opinion','weak','{"note": "1x/week"}'::jsonb,'Garage Strength - How To Snatch Like Lasha Talakhadze'),
  ('olympic','behind_neck_jerk_prescription','The behind-the-neck jerk (including behind-the-neck power jerk from boxes) is prescribed 1-2x/week for 5-6 sets of 2-4 reps to build explosive upper-back and shoulder-girdle stability in throwing/field-sport athletes.','practice','weak','{"note": "1-2x/week, 5-6 sets x 2-4 reps"}'::jsonb,'Garage Strength - Top 4 Explosive Olympic Weightlifting Upper Body Exercises For Athletes'),
  ('olympic','two_pump_snatch_prescription','A ''two pump snatch'' (double eccentric dip-and-catch before the final snatch) is prescribed once per week for 5 sets of two pumps plus one full snatch, at 80-100 kg for experienced lifters, to eccentrically overload the upper back and shoulder girdle. The absolute loads are specific to advanced lifters and should not be generalized.','practice','weak','{"note": "1x/week, 5 sets of 2 pumps + 1 snatch, 80-100 kg"}'::jsonb,'Garage Strength - Top 4 Explosive Olympic Weightlifting Upper Body Exercises For Athletes'),
  ('olympic','behind_neck_push_press_progression','The behind-the-neck push press is called the most technically demanding of the upper-body Olympic variations: start light to learn the pattern, then manipulate the eccentric - remove it by driving onto jerk boxes to allow heavier loads without added fatigue near a competition peak, or keep it in when more fatigue stimulus is wanted.','practice','weak',NULL,'Garage Strength - Top 4 Explosive Olympic Weightlifting Upper Body Exercises For Athletes'),
  ('olympic','push_press_as_jerk_teaching_tool','The push press is recommended as a slower-speed derivative for teaching jerk mechanics - dynamic trunk control, staying flat-footed through a linear drive, belly-breathing under a braced core - because reduced speed makes faults such as drifting backward visible and correctable in a way a full jerk does not.','practice','moderate',NULL,'Garage Strength - Top 3 Exercises For A Stronger Jerk In Olympic Weightlifting');

INSERT INTO public.corpus_findings
  (area, topic, claim, basis, confidence, quantities, source)
VALUES
  ('olympic','jerk_is_the_failure_point','Hand-tallied competition analysis across a dozen-plus sessions at the 2019 junior and senior world championships: 162+ missed clean and jerk attempts, 55% overall success rate, and more than 85% of misses were failures on the JERK portion rather than the clean. Self-collected by a coach, not peer-reviewed, but directly actionable for prioritizing jerk work.','practice (self-collected observational data)','moderate','{"note": "162 missed lifts; 55% success rate; >85% of misses on the jerk"}'::jsonb,'Garage Strength - Top 3 Exercises For A Stronger Jerk In Olympic Weightlifting'),
  ('olympic','overhead_lockout_failure_rate','Putsov''s graduate research on competitive efficiency found around 30% of all unsuccessful SNATCH attempts were caused by failure to hold the bar stable overhead and standing up too early - which is why he drills a 3-second pause in the bottom of the overhead squat with recreational lifters. Together with the jerk-miss data above, both lifts fail most often in the overhead receiving/stabilization phase, not the pull.','study (author''s own, secondhand relay)','moderate','{"note": "~30% of snatch misses; 3-second bottom pause"}'::jsonb,'Garage Strength - Dr. Sergii Putsov podcast'),
  ('olympic','snatch_fault_taxonomy','Three distinct systemic snatch faults each require a DIFFERENT corrective: (1) missing behind, from the hips rising too fast; (2) missing in front, from jumping backward; (3) pressing out the catch, from a weak or late triceps-to-shoulder connection - attributed to an imprecise pull path plus insufficient long-head triceps and rhomboid/upper-back strength. Implication for an app: a generic ''snatch technique'' cue set is inadequate; fault diagnosis must precede drill selection.','practice + mechanistic','moderate',NULL,'Garage Strength - 3 BIGGEST Olympic Lifting Mistakes Everyone Makes; Improve Your Lockout | Snatch Workout For Weightlifting'),
  ('olympic','mobility_gates_before_loading','Consistent across two independent sources: the front-rack and overhead positions are the gating constraint, not strength. Restricted wrist, elbow, triceps, lat, thoracic, hip, ankle, and lower-back mobility prevent a proper front rack or floor start. Remedies given: an unloaded overhead squat as the first screen for any new lifter (chest dropping forward = fail), substituting a ''zombie squat'' arm position for front squats, and - for lifters from a heavy bench-press background - deliberately REDUCING bench volume to restore the mobility needed for the front rack.','practice (two independent sources)','moderate',NULL,'Juggernaut - SuperTotal Training; Garage Strength - Putsov podcast; Top 4 Strength Exercises Every Athlete Should Do!'),
  ('olympic','snatch_before_clean','Teach the snatch before the clean, for two stated reasons: the overhead position immediately exposes ankle and shoulder mobility limits (visible as the chest dropping in an overhead squat), and athletes with tight wrists and upper backs (e.g. football players) reach the snatch''s overhead position more easily than the clean''s front rack - so they often learn the snatch faster.','practice','moderate',NULL,'Garage Strength - How To Snatch For Beginners and Elites; Top 4 Strength Exercises Every Athlete Should Do!'),
  ('olympic','snatch_teaching_progression_garage_strength','Full beginner snatch progression: set grip width so the bar sits at the hip crease ? standing snatch presses (2-3 sets of 5-10 reps) to find the overhead catch ? overhead squat (~5 reps) for overhead stability ? snatch balance for drive and change of direction ? muscle snatch ? hip power snatch into an overhead-squat catch ? full hip snatch (triples) ? paused-position full snatches ? full snatch from the floor.','practice','moderate','{"note": "snatch press 2-3 x 5-10; overhead squat ~5 reps; hip snatch in triples"}'::jsonb,'Garage Strength - How To Snatch For Beginners and Elites'),
  ('olympic','beginner_progression_putsov','Putsov''s first-session progression for a total beginner: assess grip and overhead position ? unloaded overhead squat as mobility/coordination screen (hip vs knee initiation, depth, balance) ? tall muscle snatch for upper-body mechanics ? tall muscle snatch combined with overhead squat ? introduce the ''point of contact'' concept ? and ONLY if coordination is good, finish with a hang power snatch caught from above the knee. Broadly agrees with the Garage Strength progression on the overhead-squat screen and muscle snatch, but stops well short of the floor on day one.','practice','moderate',NULL,'Garage Strength - Dr. Sergii Putsov podcast'),
  ('olympic','floor_start_day_one_contested','CONTESTED - the sharpest disagreement in this area. Dane Miller has beginners attempt the COMPLETE snatch from the floor with a PVC pipe or light bar on session one, arguing this accelerates technical learning even though the lift will not be clean for years. Putsov explicitly avoids teaching lifts from the floor until lower-back, ankle, hip, and thoracic mobility improve, and instead lowers beginners eccentrically from the power position to just below the knee, arguing eccentric loading recruits more muscle and is easier for a beginner''s nervous system to learn from. An app must pick a side or gate on the mobility screen.','opinion vs practice - direct conflict','moderate',NULL,'Garage Strength - How To Snatch For Beginners and Elites vs Dr. Sergii Putsov podcast'),
  ('olympic','youth_teaching_age_contested','CONTESTED. Dane Miller says he has coached Olympic-lift technique to athletes as young as 8-10 years old and calls coaches who avoid the lifts as ''too hard'' a disservice to athletes. Putsov warns that youth lifters chasing records and specializing early are frequently overtrained, injured, and ''already hate weightlifting'' by ~age 21, and so restricts his own 15-19 year olds'' early years to general physical preparation (push-ups, pull-ups, air-bike intervals, broad jumps) rather than heavy technical lift work. The cited 28-week study on 12-14 year olds found little added benefit from weightlifting, which leans toward Putsov.','opinion vs practice - direct conflict, with study leaning one way','moderate','{"note": "Miller: ages 8-10 up; Putsov: GPP focus through ages 15-19"}'::jsonb,'Garage Strength - Weightlifting For Sports | What Strength Coaches GET WRONG! vs Dr. Sergii Putsov podcast'),
  ('olympic','general_prep_before_specialization','Putsov states the first 3-4 years of an athlete''s training should target general physical preparation - speed, power, coordination, flexibility, endurance - before sport-specific or Olympic-lift-specific skill, because a deficiency in any general quality creates problems later.','practice','moderate','{"note": "first 3-4 years"}'::jsonb,'Garage Strength - Dr. Sergii Putsov podcast'),
  ('olympic','technique_acquisition_timeline','Time-to-competence estimate: roughly 30-40 minutes of dedicated technique work per training day for about a month, with the whole progression repeated multiple times over 2-3 months, before technical breakthroughs occur. Uncited coach estimate but the only explicit learning-curve number in the corpus.','opinion','weak','{"note": "30-40 min/day for ~1 month; progression repeated over 2-3 months"}'::jsonb,'Garage Strength - How To Snatch For Beginners and Elites'),
  ('olympic','session_time_allocation_for_learners','A strength athlete new to weightlifting should spend roughly half or more of session time on drills, mobility, and technical progressions before loaded lift work - ''at least an hour'' of a normally two-hour session.','practice','moderate','{"note": "?1 hour of a 2-hour session"}'::jsonb,'Juggernaut - SuperTotal Training | Adding Weightlifting for Powerlifters'),
  ('olympic','technique_first_in_session','Olympic-lift technique work should always be placed FIRST in a session, before other lifts, so it is performed at minimum fatigue.','practice','moderate',NULL,'Juggernaut - SuperTotal Training | Adding Weightlifting for Powerlifters'),
  ('olympic','one_lift_per_day_for_learners','For a lifter still learning, dedicate each session to a single Olympic lift - a snatch day, a separate clean day, a separate jerk day - rather than combining snatch and clean-and-jerk work, because the two lifts differ enough that combining them during the learning phase interferes with technique and timing.','practice','moderate',NULL,'Juggernaut - SuperTotal Training | Adding Weightlifting for Powerlifters'),
  ('olympic','drop_competing_volume_while_learning','Carrying near-maximal volume on other main lifts while learning Olympic technique is counterproductive - a persistently fatigued athlete struggles to acquire new motor skill - so competing lifts should be dropped to maintenance volume for the duration technique is being learned.','practice','moderate',NULL,'Juggernaut - SuperTotal Training | Adding Weightlifting for Powerlifters'),
  ('olympic','intensity_floor_by_level','Putsov counts training volume from 50% of 1RM for amateur/recreational lifters - because he considers those lighter intensities where movement quality is learned - versus counting from 70% for national-team athletes, and cites Pyrros Dimas''s view that at professional level ''below 80% is for beginners.'' Directly usable as a level-dependent volume-counting threshold.','practice','moderate','{"note": "50% floor (recreational); 70% floor (national team); 80% (elite view)"}'::jsonb,'Garage Strength - Dr. Sergii Putsov podcast'),
  ('olympic','squat_frequency_ceiling','Putsov caps even elite lifters at three squat sessions per week during high-volume blocks, arguing heavy brute-strength loading (squats and pulls) makes a lifter stronger but ''kills your speed, over-exhausts your nervous system, and increases risk of injury'' - so squat loading is balanced, not maximized.','practice','moderate','{"note": "max 3 squat sessions/week"}'::jsonb,'Garage Strength - Dr. Sergii Putsov podcast'),
  ('olympic','elite_frequency_not_transferable','Explicit anti-transfer warning: twice-daily Olympic lifting only works when an athlete''s whole life is arranged around it (living at a training base, no job, no commute), and attempting the same frequency on a normal daily schedule ''will not work.'' An app should not surface elite-frequency templates to general users.','practice','moderate',NULL,'Garage Strength - Dr. Sergii Putsov podcast'),
  ('olympic','variation_programming_frequency','Derivative/variation lifts (snatch pulls, deficit snatch, low-hang snatch, no-feet cleans, power snatches/cleans) are programmed two to three days per week alongside the competitive lifts, with the specific variation chosen to target the individual''s weakness: strength off the floor, technical precision, force absorption, or trunk control.','practice','moderate','{"note": "2-3 days/week"}'::jsonb,'Garage Strength - How To Program Variation Exercises For Olympic Lifting'),
  ('olympic','variation_injury_rationale','Rationale given for rotating variations: performing only the classical snatch and clean & jerk repeatedly is claimed to cause overuse injury and technical staleness, whereas derivatives supply new adaptation stimuli and are intended to reduce injury risk. No injury data is offered to support this - it is a coaching rationale, not evidence.','practice (unsupported by data in corpus)','weak',NULL,'Garage Strength - Why You Should Train Variation Exercises For Olympic Weightlifting'),
  ('olympic','derivative_technical_demand_tiers','Barbell power movements are categorized into three tiers of technical demand, a directly usable difficulty ladder for an app: (1) competitive lifts - snatch, clean, jerk; (2) simpler variations - power snatch, power clean, hang clean, behind-the-neck jerk; (3) ''reflexive'' variations - e.g. dumbbell drop snatch - that train force absorption with the least coaching required.','practice','moderate','{"note": "3 tiers"}'::jsonb,'Garage Strength - Top 4 Weightlifting Exercises For Sprinting'),
  ('olympic','derivatives_substitute_for_full_lift','Field-sport athletes do not need the full snatch to obtain its coordination benefits and can substitute high-hang power snatches, two-box power snatches, a general power snatch, or a dumbbell snatch. Note this coaching position sits in tension with the cited 10-week catch-vs-pull study, which found full catch versions outperformed no-catch derivatives.','practice (tension with cited study)','moderate',NULL,'Garage Strength - Top 4 Strength Exercises Every Athlete Should Do!'),
  ('olympic','catch_depth_by_sport','Catch depth is prescribed by sport demand: basketball and volleyball players use high-hang power snatches without catching in a full squat, while shot putters and wrestlers catch the snatch at full depth.','practice','moderate',NULL,'Garage Strength - Top 4 Strength Exercises Every Athlete Should Do!'),
  ('olympic','front_squat_priority','Pause front squats are ranked the single best exercise for developing pulling strength and receiving-position stability, ahead of pause back squats and box squats, with front-squat foot stance set to match the lifter''s clean-catch stance.','opinion','weak',NULL,'Garage Strength - The ONLY Olympic Weightlifting Program You''ll Ever Need'),
  ('olympic','triple_flexion_vs_triple_extension','CONTESTED coaching philosophy. Al Vermeil (Chicago Bulls six championships, Bears Super Bowl) argued the TRIPLE FLEXION catch position (ankle dorsiflexion, knee flexion, hip flexion) is more transferable to sport than the lift''s triple-extension finish, because it mirrors the loaded low defensive stance athletes must be strongest in. Separately, one coach argues triple extension should NEVER be directly cued and should emerge as a byproduct of correct earlier-pull positioning - ''cueing the finish is just putting a band-aid over the problem.'' Both positions undercut the common triple-extension-focused cueing an app might default to.','opinion (two coaches, contested)','weak',NULL,'Garage Strength - The Common GYM TIP That RUINS Your Strength Gains!');

INSERT INTO public.corpus_findings
  (area, topic, claim, basis, confidence, quantities, source)
VALUES
  ('olympic','knee_over_toe_catch_safety','One coach argues Olympic-lift catch positions requiring knees to travel past the toes are not a safety concern as long as the heels stay grounded, comparing it to normal walking, running, and stair-climbing mechanics. Opinion only, no data cited; relevant if an app surfaces knee-over-toe warnings.','opinion','weak',NULL,'Garage Strength - Weightlifting For Sports | What Strength Coaches GET WRONG!'),
  ('olympic','landmine_vs_bilateral_contested','CONTESTED. The founder of ''Landmine University'' presents landmine rotational exercises as a more functional and easier-to-teach substitute for bilateral Olympic lifts for combat-sport athletes (boxing, wrestling, MMA). The counter-argument raised in the same video: MMA fighters Lyoto Machida and Georges St-Pierre both trained bilateral Olympic movements, and a two-time world bronze medalist freestyle wrestler cleaned 360 lb bilaterally - offered as evidence bilateral strength carries to a single-leg wrestling stance. Both sides are anecdote; no data either way.','opinion vs opinion, both anecdotal','weak','{"note": "360 lb clean (wrestler anecdote)"}'::jsonb,'Garage Strength - Is LANDMINE Training The SECRET To Athletic Performance?'),
  ('olympic','strength_without_deadlift','A coach claims athletes can build absolute strength - citing a 700 lb PR deadlift - without ever training the conventional deadlift directly, using cleans, front squats, back squats, and jumps instead. Single uncited anecdote; relevant only as a hypothesis that Olympic lifts can occupy a deadlift''s programming slot.','opinion (n=1 anecdote)','weak','{"note": "700 lb deadlift"}'::jsonb,'Garage Strength - Weightlifting For Sports | What Strength Coaches GET WRONG!'),
  ('olympic','snatch_drop_time','The ''drop time'' from the top of the snatch pull to the catch is asserted to be about 0.4 seconds, with the coach arguing this speed trains central pattern generators involved in athletic coordination. The 0.4 s figure is plausible and usable as a descriptor; the CPG mechanism is speculative and uncited.','mechanistic (speculative)','weak','{"note": "~0.4 seconds"}'::jsonb,'Garage Strength - Top 4 Strength Exercises Every Athlete Should Do!'),
  ('olympic','transfer_mechanism_rationale','The mechanistic case offered for why Olympic lifting transfers to sport: the lift chains isometric tension off the floor, concentric hip extension, and eccentric force ABSORPTION into a stretch-shortening catch, training an athlete''s general ability to absorb and reuse force. This is coach rationale, not evidence, but it is the mechanism the corpus''s derivative-selection logic (force absorption drills, catch depth by sport) is built on.','opinion (mechanistic rationale)','weak',NULL,'Garage Strength - Weightlifting For Sports | What Strength Coaches GET WRONG!');
